package com.gazellio.platform.service;

import java.util.*;

public final class PermissionCatalog {
    private PermissionCatalog() {}
    public static final Set<String> LEGACY=Set.of("VULNERABILITY_MANAGE","INCIDENT_MANAGE","CHANGE_MANAGE","TASK_MANAGE","PATCH_MANAGE","AUTOMATION_EXECUTE");
    public static final List<String> ALL=List.of(
            "DASHBOARD_VIEW",
            "VULNERABILITY_VIEW","VULNERABILITY_CONFIRM","VULNERABILITY_FALSE_POSITIVE",
            "VULNERABILITY_EXEMPT","VULNERABILITY_EXPORT","VULNERABILITY_INTEL_SYNC",
            "SCAN_VIEW","SCAN_EXECUTE",
            "ASSET_VIEW","ASSET_SYNC",
            "INCIDENT_VIEW","INCIDENT_CREATE","INCIDENT_ASSIGN","INCIDENT_REMEDIATE",
            "CHANGE_VIEW","CHANGE_CREATE","CHANGE_RESUBMIT",
            "TASK_VIEW","TASK_ASSIGN","TASK_EXECUTE","TASK_RETEST",
            "PATCH_VIEW","PATCH_REGISTER","PATCH_CATALOG_SYNC","PATCH_SCHEDULE","PATCH_DEPLOY",
            "APPROVAL_VIEW","APPROVAL_ACT",
            "AUTOMATION_VIEW","AUTOMATION_RUN_CONTROL","AUTOMATION_TEMPLATE_EDIT",
            "REPORT_VIEW","REPORT_EXPORT","AUDIT_VIEW","AUDIT_EXPORT",
            "SETTINGS_VIEW","SETTINGS_MANAGE",
            "USER_MANAGE","ROLE_MANAGE","USER_CREDENTIAL_RESET","USER_ACCOUNT_STATUS"
    );
    public static List<String> defaults(String role){
        return switch(role){
            case "ADMIN" -> ALL;
            case "SECURITY" -> List.of("DASHBOARD_VIEW","VULNERABILITY_VIEW","VULNERABILITY_CONFIRM","VULNERABILITY_FALSE_POSITIVE","VULNERABILITY_EXEMPT","VULNERABILITY_EXPORT","VULNERABILITY_INTEL_SYNC","SCAN_VIEW","SCAN_EXECUTE","ASSET_VIEW","ASSET_SYNC","INCIDENT_VIEW","INCIDENT_CREATE","INCIDENT_ASSIGN","INCIDENT_REMEDIATE","CHANGE_VIEW","CHANGE_CREATE","TASK_VIEW","TASK_ASSIGN","TASK_RETEST","PATCH_VIEW","PATCH_REGISTER","PATCH_CATALOG_SYNC","PATCH_SCHEDULE","APPROVAL_VIEW","APPROVAL_ACT","AUTOMATION_VIEW","REPORT_VIEW","REPORT_EXPORT","AUDIT_VIEW","AUDIT_EXPORT","SETTINGS_VIEW");
            case "OPS" -> List.of("DASHBOARD_VIEW","VULNERABILITY_VIEW","SCAN_VIEW","ASSET_VIEW","INCIDENT_VIEW","INCIDENT_REMEDIATE","CHANGE_VIEW","CHANGE_CREATE","CHANGE_RESUBMIT","TASK_VIEW","TASK_ASSIGN","TASK_EXECUTE","TASK_RETEST","PATCH_VIEW","PATCH_REGISTER","PATCH_CATALOG_SYNC","PATCH_SCHEDULE","PATCH_DEPLOY","APPROVAL_VIEW","APPROVAL_ACT","AUTOMATION_VIEW","AUTOMATION_RUN_CONTROL","AUTOMATION_TEMPLATE_EDIT","REPORT_VIEW","REPORT_EXPORT");
            case "APPROVER" -> List.of("DASHBOARD_VIEW","VULNERABILITY_VIEW","ASSET_VIEW","INCIDENT_VIEW","CHANGE_VIEW","TASK_VIEW","PATCH_VIEW","APPROVAL_VIEW","APPROVAL_ACT","AUTOMATION_VIEW","REPORT_VIEW");
            default -> List.of("DASHBOARD_VIEW","VULNERABILITY_VIEW","ASSET_VIEW","INCIDENT_VIEW","CHANGE_VIEW","TASK_VIEW","TASK_RETEST","PATCH_VIEW","AUTOMATION_VIEW","REPORT_VIEW");
        };
    }
    public static boolean isKnown(String permission){return ALL.contains(permission)||LEGACY.contains(permission);}
}
