package com.gazellio.platform.service;

import java.util.*;

public final class PermissionCatalog {
    private PermissionCatalog() {}
    public static final List<String> ALL=List.of(
            "DASHBOARD_VIEW","VULNERABILITY_VIEW","VULNERABILITY_MANAGE","SCAN_VIEW","SCAN_EXECUTE",
            "ASSET_VIEW","ASSET_SYNC","INCIDENT_VIEW","INCIDENT_MANAGE","CHANGE_VIEW","CHANGE_MANAGE",
            "TASK_VIEW","TASK_MANAGE","PATCH_VIEW","PATCH_MANAGE","PATCH_SCHEDULE",
            "APPROVAL_VIEW","APPROVAL_ACT","AUTOMATION_VIEW","AUTOMATION_EXECUTE","AUTOMATION_TEMPLATE_EDIT",
            "REPORT_VIEW","AUDIT_VIEW","SETTINGS_VIEW","SETTINGS_MANAGE","USER_MANAGE"
    );
    public static List<String> defaults(String role){
        return switch(role){
            case "ADMIN" -> ALL;
            case "SECURITY" -> List.of("DASHBOARD_VIEW","VULNERABILITY_VIEW","VULNERABILITY_MANAGE","SCAN_VIEW","SCAN_EXECUTE","ASSET_VIEW","ASSET_SYNC","INCIDENT_VIEW","INCIDENT_MANAGE","CHANGE_VIEW","TASK_VIEW","PATCH_VIEW","PATCH_MANAGE","PATCH_SCHEDULE","APPROVAL_VIEW","APPROVAL_ACT","AUTOMATION_VIEW","REPORT_VIEW","AUDIT_VIEW","SETTINGS_VIEW");
            case "OPS" -> List.of("DASHBOARD_VIEW","VULNERABILITY_VIEW","SCAN_VIEW","ASSET_VIEW","INCIDENT_VIEW","CHANGE_VIEW","CHANGE_MANAGE","TASK_VIEW","TASK_MANAGE","PATCH_VIEW","PATCH_MANAGE","PATCH_SCHEDULE","APPROVAL_VIEW","APPROVAL_ACT","AUTOMATION_VIEW","AUTOMATION_EXECUTE","AUTOMATION_TEMPLATE_EDIT","REPORT_VIEW");
            case "APPROVER" -> List.of("DASHBOARD_VIEW","VULNERABILITY_VIEW","ASSET_VIEW","INCIDENT_VIEW","CHANGE_VIEW","TASK_VIEW","PATCH_VIEW","APPROVAL_VIEW","APPROVAL_ACT","AUTOMATION_VIEW","REPORT_VIEW");
            default -> List.of("DASHBOARD_VIEW","VULNERABILITY_VIEW","ASSET_VIEW","INCIDENT_VIEW","TASK_VIEW","PATCH_VIEW","AUTOMATION_VIEW");
        };
    }
}
