import React,{useEffect,useRef,useState} from 'react'
import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { LayoutDashboard, ShieldAlert, Library, ScanSearch, ClipboardList, Package, CheckSquare, Workflow, BarChart3, Settings, ScrollText, Search, Bell, LogOut, ChevronDown, TicketCheck, FileClock, CalendarDays, Network, Server, Users } from 'lucide-react'
import { useI18n } from '../contexts/I18nContext'
import { useAuth } from '../contexts/AuthContext'
import {api} from '../api/client'

const groups=[
 {key:'vulnerabilityManagement',items:[['/vulnerabilities/library','vulnerabilityLibrary',Library,'VULNERABILITY_VIEW'],['/vulnerabilities/findings','findings',ShieldAlert,'VULNERABILITY_VIEW'],['/scans','scanManagement',ScanSearch,'SCAN_VIEW']]},
 {key:'assetManagement',items:[['/assets','cmdb',Server,'ASSET_VIEW']]},
 {key:'workOrderCenter',items:[['/work-orders/incidents','securityIncidents',TicketCheck,'INCIDENT_VIEW'],['/work-orders/changes','changeOrders',FileClock,'CHANGE_VIEW']]},
 {key:'remediation',items:[['/tasks','tasks',ClipboardList,'TASK_VIEW'],['/patches','patchCenter',Package,'PATCH_VIEW'],['/patches/calendar','patchCalendar',CalendarDays,'PATCH_VIEW'],['/automation/batch','batchPatch',Network,'AUTOMATION_EXECUTE'],['/approvals','approvals',CheckSquare,'APPROVAL_VIEW'],['/automation','automation',Workflow,'AUTOMATION_VIEW']]},
 {key:null,items:[['/reports','reports',BarChart3,'REPORT_VIEW'],['/audit','audit',ScrollText,'AUDIT_VIEW'],['/settings','settings',Settings,'SETTINGS_VIEW'],['/settings/access','accessControl',Users,'USER_MANAGE']]}
]
export default function Layout(){
 const {t,lang,setLang,localize}=useI18n();const {user,logout,has}=useAuth();const nav=useNavigate();const [q,setQ]=useState(''),[results,setResults]=useState([]),[searching,setSearching]=useState(false),[open,setOpen]=useState(false);const searchRef=useRef(null)
 useEffect(()=>{if(q.trim().length<2){setResults([]);setOpen(false);return}let active=true;const timer=setTimeout(async()=>{setSearching(true);try{const data=await api('/api/search?q='+encodeURIComponent(q.trim()));if(active){setResults(data||[]);setOpen(true)}}catch{if(active)setResults([])}finally{if(active)setSearching(false)}},250);return()=>{active=false;clearTimeout(timer)}},[q])
 useEffect(()=>{const close=e=>{if(!searchRef.current?.contains(e.target))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[])
 const go=item=>{setOpen(false);setQ('');nav(item.path)}
 const submit=e=>{e.preventDefault();if(results[0])go(results[0]);else if(q.trim())nav('/vulnerabilities/library?q='+encodeURIComponent(q.trim()))}
 const typeLabel=type=>t(`searchType_${type}`)
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><img src="/gazellio-logo.png" alt="Gazellio"/></div><nav>{has('DASHBOARD_VIEW')&&<NavLink to="/" end className={({isActive})=>`nav-link ${isActive?'active':''}`}><LayoutDashboard/><span>{t('dashboard')}</span></NavLink>}{groups.map((g,gi)=>{const items=g.items.filter(([, , ,permission])=>has(permission));return items.length?<div className="nav-group" key={gi}>{g.key&&<div className="nav-group-title">{t(g.key)}</div>}{items.map(([to,key,Icon])=><NavLink key={to} to={to} end={to==='/patches'||to==='/automation'||to==='/settings'} className={({isActive})=>`nav-link ${isActive?'active':''}`}><Icon/><span>{t(key)}</span></NavLink>)}</div>:null})}</nav><div className="sidebar-health"><span className="health-dot"/><span>{t('normal')}</span></div></aside><main className="main"><header className="topbar"><div className="global-search-wrap" ref={searchRef}><form className="global-search" onSubmit={submit}><Search size={17}/><input value={q} onFocus={()=>q.trim().length>=2&&setOpen(true)} onChange={e=>setQ(e.target.value)} placeholder={t('globalSearch')}/></form>{open&&<div className="global-search-results">{searching?<div className="search-empty">{t('searching')}</div>:results.length?results.map(item=><button key={`${item.type}-${item.id}`} onClick={()=>go(item)}><span className="search-type">{typeLabel(item.type)}</span><span className="search-copy"><b>{localize(lang==='zh'?item.titleZh:item.titleEn)}</b><small>{localize(lang==='zh'?item.subtitleZh:item.subtitleEn)}</small></span></button>):<div className="search-empty">{t('noSearchResults')}</div>}</div>}</div><div className="top-actions"><button className="lang-toggle" onClick={()=>setLang(lang==='zh'?'en':'zh')}>{lang==='zh'?t('switchToEnglish'):t('switchToChinese')}</button><button className="icon-button"><Bell size={18}/><span className="bell-dot"/></button><div className="user-box"><div className="avatar">{(user?.displayName||'GA').slice(0,2).toUpperCase()}</div><div className="user-copy"><b>{user?.displayName||'Gazellio'}</b><small>{lang==='zh'?(user?.roleNameZh||user?.role):(user?.roleNameEn||user?.role)}</small></div><ChevronDown size={14}/><button className="logout-button" title={t('logout')} onClick={logout}><LogOut size={16}/></button></div></div></header><section className="content"><Outlet/></section></main></div>
}
