import React,{useMemo,useState} from 'react'
import {KeyRound,Plus,RotateCcw,ShieldCheck,Trash2,UserRound} from 'lucide-react'
import {api} from '../api/client'
import {useApiData} from '../utils/useApiData'
import {useI18n} from '../contexts/I18nContext'
import {useToast} from '../components/ToastContext'
import PageHeader from '../components/PageHeader'
import DataTable from '../components/DataTable'
import Modal from '../components/Modal'
import StatusBadge from '../components/StatusBadge'

const emptyUser={username:'',displayName:'',email:'',roleId:'',enabled:true,password:''}
const emptyRole={code:'',nameZh:'',nameEn:'',enabled:true,permissions:[]}
const permissionGroups=['DASHBOARD','VULNERABILITY','SCAN','ASSET','INCIDENT','CHANGE','TASK','PATCH','APPROVAL','AUTOMATION','REPORT','AUDIT','SETTINGS','USER']

export default function AccessControlPage(){
 const {t,lang}=useI18n(),toast=useToast();const [tab,setTab]=useState('users'),[userForm,setUserForm]=useState(null),[roleForm,setRoleForm]=useState(null),[busy,setBusy]=useState(false)
 const {data:users=[],reload:reloadUsers}=useApiData('/api/access-control/users',{initial:[]});const {data:roles=[],reload:reloadRoles}=useApiData('/api/access-control/roles',{initial:[]});const {data:permissions=[]}=useApiData('/api/access-control/permissions',{initial:[]})
 const enabledRoles=roles.filter(r=>r.enabled);const grouped=useMemo(()=>permissionGroups.map(group=>({group,items:permissions.filter(p=>p.startsWith(group+'_'))})).filter(x=>x.items.length),[permissions])
 const saveUser=async()=>{setBusy(true);try{const edit=!!userForm.id;await api(`/api/access-control/users${edit?`/${userForm.id}`:''}`,{method:edit?'PUT':'POST',body:{...userForm,roleId:Number(userForm.roleId),password:userForm.password||null}});setUserForm(null);await Promise.all([reloadUsers(),reloadRoles()]);toast.push(t('userSaved'))}catch(e){toast.push(e.message,'red')}finally{setBusy(false)}}
 const saveRole=async()=>{setBusy(true);try{const edit=!!roleForm.id;await api(`/api/access-control/roles${edit?`/${roleForm.id}`:''}`,{method:edit?'PUT':'POST',body:roleForm});setRoleForm(null);await Promise.all([reloadRoles(),reloadUsers()]);toast.push(t('roleSaved'))}catch(e){toast.push(e.message,'red')}finally{setBusy(false)}}
 const remove=async(type,id)=>{if(!window.confirm(t(type==='users'?'confirmDeleteUser':'confirmDeleteRole')))return;try{await api(`/api/access-control/${type}/${id}`,{method:'DELETE'});await Promise.all([reloadUsers(),reloadRoles()]);toast.push(t('operationSuccess'))}catch(e){toast.push(e.message,'red')}}
 const reset=async id=>{if(!window.confirm(t('confirmResetPassword')))return;try{await api(`/api/access-control/users/${id}/reset-password`,{method:'POST'});toast.push(t('passwordReset'))}catch(e){toast.push(e.message,'red')}}
 const userCols=[{key:'username',label:t('username'),render:r=><div className="cell-main"><b>{r.username}</b><small>{r.email||'—'}</small></div>},{key:'displayName',label:t('displayName'),render:r=><b>{r.displayName}</b>},{key:'role',label:t('role'),render:r=><span>{lang==='zh'?r.roleNameZh:r.roleNameEn}</span>},{key:'permissions',label:t('permissions'),render:r=>r.permissions?.length||0},{key:'enabled',label:t('status'),render:r=><StatusBadge tone={r.enabled?'ok':'gray'}>{r.enabled?t('enabled'):t('disabled')}</StatusBadge>},{key:'actions',label:t('action'),render:r=><div className="row-actions"><button className="btn small" onClick={e=>{e.stopPropagation();setUserForm({...r,password:''})}}>{t('edit')}</button><button className="btn small" title={t('resetPassword')} onClick={e=>{e.stopPropagation();reset(r.id)}}><RotateCcw size={13}/></button><button className="btn small danger" disabled={r.username==='admin'} onClick={e=>{e.stopPropagation();remove('users',r.id)}}><Trash2 size={13}/></button></div>}]
 const roleCols=[{key:'code',label:t('roleCode'),render:r=><span className="mono">{r.code}</span>},{key:'name',label:t('name'),render:r=><div className="cell-main"><b>{lang==='zh'?r.nameZh:r.nameEn}</b><small>{lang==='zh'?r.nameEn:r.nameZh}</small></div>},{key:'userCount',label:t('users'),render:r=>r.userCount},{key:'permissions',label:t('permissions'),render:r=>r.permissions?.length||0},{key:'enabled',label:t('status'),render:r=><StatusBadge tone={r.enabled?'ok':'gray'}>{r.enabled?t('enabled'):t('disabled')}</StatusBadge>},{key:'actions',label:t('action'),render:r=><div className="row-actions"><button className="btn small" onClick={e=>{e.stopPropagation();setRoleForm({...r,permissions:[...(r.permissions||[])]})}}>{t('edit')}</button><button className="btn small danger" disabled={r.systemRole||r.userCount>0} onClick={e=>{e.stopPropagation();remove('roles',r.id)}}><Trash2 size={13}/></button></div>}]
 return <><PageHeader title={t('accessControl')}><button className="btn primary" onClick={()=>tab==='users'?setUserForm({...emptyUser,roleId:enabledRoles[0]?.id||''}):setRoleForm({...emptyRole})}><Plus size={15}/>{tab==='users'?t('newUser'):t('newRole')}</button></PageHeader><div className="access-summary"><div><UserRound/><span>{t('users')}</span><b>{users.length}</b></div><div><ShieldCheck/><span>{t('roles')}</span><b>{roles.length}</b></div><div><KeyRound/><span>{t('permissions')}</span><b>{permissions.length}</b></div></div><div className="tabs"><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>{t('users')}<span>{users.length}</span></button><button className={tab==='roles'?'active':''} onClick={()=>setTab('roles')}>{t('roles')}<span>{roles.length}</span></button></div><DataTable columns={tab==='users'?userCols:roleCols} rows={tab==='users'?users:roles}/>
 <Modal open={!!userForm} title={userForm?.id?t('editUser'):t('newUser')} onClose={()=>setUserForm(null)} footer={<><button className="btn" onClick={()=>setUserForm(null)}>{t('cancel')}</button><button className="btn primary" disabled={busy||!userForm?.username||!userForm?.displayName||!userForm?.roleId} onClick={saveUser}>{t('save')}</button></>}><div className="form-grid"><label className="form-field"><span>{t('username')}</span><input value={userForm?.username||''} onChange={e=>setUserForm({...userForm,username:e.target.value})}/></label><label className="form-field"><span>{t('displayName')}</span><input value={userForm?.displayName||''} onChange={e=>setUserForm({...userForm,displayName:e.target.value})}/></label><label className="form-field"><span>{t('email')}</span><input value={userForm?.email||''} onChange={e=>setUserForm({...userForm,email:e.target.value})}/></label><label className="form-field"><span>{t('role')}</span><select value={userForm?.roleId||''} onChange={e=>setUserForm({...userForm,roleId:e.target.value})}>{enabledRoles.map(r=><option key={r.id} value={r.id}>{lang==='zh'?r.nameZh:r.nameEn}</option>)}</select></label><label className="form-field full"><span>{userForm?.id?t('newPasswordOptional'):t('initialPassword')}</span><input type="password" value={userForm?.password||''} placeholder="Gazellio@123" onChange={e=>setUserForm({...userForm,password:e.target.value})}/></label><label className="check-field full"><input type="checkbox" checked={!!userForm?.enabled} onChange={e=>setUserForm({...userForm,enabled:e.target.checked})}/>{t('enabled')}</label></div></Modal>
 <Modal open={!!roleForm} size="lg" title={roleForm?.id?t('editRole'):t('newRole')} onClose={()=>setRoleForm(null)} footer={<><button className="btn" onClick={()=>setRoleForm(null)}>{t('cancel')}</button><button className="btn primary" disabled={busy||!roleForm?.code||!roleForm?.nameZh||!roleForm?.nameEn} onClick={saveRole}>{t('save')}</button></>}><div className="form-grid"><label className="form-field"><span>{t('roleCode')}</span><input value={roleForm?.code||''} onChange={e=>setRoleForm({...roleForm,code:e.target.value})}/></label><label className="check-field"><input type="checkbox" checked={!!roleForm?.enabled} onChange={e=>setRoleForm({...roleForm,enabled:e.target.checked})}/>{t('enabled')}</label><label className="form-field"><span>{t('titleZh')}</span><input value={roleForm?.nameZh||''} onChange={e=>setRoleForm({...roleForm,nameZh:e.target.value})}/></label><label className="form-field"><span>{t('titleEn')}</span><input value={roleForm?.nameEn||''} onChange={e=>setRoleForm({...roleForm,nameEn:e.target.value})}/></label><div className="permission-editor full">{grouped.map(({group,items})=><section key={group}><b>{t(`permissionGroup_${group}`)}</b><div>{items.map(permission=><label className="check-field" key={permission}><input type="checkbox" checked={roleForm?.permissions?.includes(permission)||false} onChange={e=>setRoleForm({...roleForm,permissions:e.target.checked?[...(roleForm.permissions||[]),permission]:(roleForm.permissions||[]).filter(x=>x!==permission)})}/>{t(`permission_${permission}`)}</label>)}</div></section>)}</div></div></Modal></>
}
