import React,{useMemo,useState} from 'react'
import { RefreshCw } from 'lucide-react'
import { useApiData } from '../utils/useApiData'
import { useI18n } from '../contexts/I18nContext'
import PageHeader from '../components/PageHeader'
import DataTable from '../components/DataTable'
import StatusBadge,{statusTone} from '../components/StatusBadge'
import {envLabel,fmtDate} from '../utils/format'
export default function AssetsPage(){const {t,lang}=useI18n();const {data=[],loading,reload}=useApiData('/api/assets',{initial:[]});const [q,setQ]=useState(''),[env,setEnv]=useState('ALL');const rows=useMemo(()=>data.filter(a=>(!q||(`${a.assetCode} ${a.name} ${a.ipAddress} ${a.businessService} ${a.ownerName}`).toLowerCase().includes(q.toLowerCase()))&&(env==='ALL'||a.environment===env)),[data,q,env]);const cols=[{key:'assetCode',label:t('assetCode'),render:r=><span className="mono linkish">{r.assetCode}</span>},{key:'name',label:t('asset'),render:r=><div className="cell-main"><b>{r.name}</b><small>{r.ipAddress}</small></div>},{key:'environment',label:t('environment'),render:r=><StatusBadge tone={r.environment==='PROD'?'purple':'gray'}>{envLabel(t,r.environment)}</StatusBadge>},{key:'businessService',label:t('businessService')},{key:'ownerName',label:t('owner')},{key:'osName',label:t('os'),render:r=><div className="cell-main"><b>{r.osName}</b><small>{r.osVersion}</small></div>},{key:'agentStatus',label:t('agentStatus'),render:r=><StatusBadge tone={statusTone(r.agentStatus)}>{t(String(r.agentStatus).toLowerCase())}</StatusBadge>},{key:'patchBaseline',label:t('baseline')},{key:'openFindings',label:t('openVulnerabilities')},{key:'lastSeenAt',label:t('lastSeen'),render:r=>fmtDate(r.lastSeenAt,lang)}];return <><PageHeader title={t('cmdb')}><button className="btn" onClick={reload}><RefreshCw size={15}/>{t('refresh')}</button></PageHeader><div className="toolbar"><input className="search-input" value={q} onChange={e=>setQ(e.target.value)} placeholder={`${t('search')} ${t('asset')}`}/><select value={env} onChange={e=>setEnv(e.target.value)}><option value="ALL">{t('all')} · {t('environment')}</option><option value="PROD">{t('production')}</option><option value="PREPROD">{t('preprod')}</option><option value="TEST">{t('test')}</option><option value="DEV">{t('development')}</option></select><span className="toolbar-count">{rows.length}</span></div><DataTable columns={cols} rows={rows} empty={loading?t('loading'):t('noData')}/></>}
