import React,{useState} from 'react'
import { ArrowLeft, Pause, Play, RotateCcw, ExternalLink, Server } from 'lucide-react'
import { useNavigate,useParams } from 'react-router-dom'
import { useApiData } from '../utils/useApiData'
import { api } from '../api/client'
import { useI18n } from '../contexts/I18nContext'
import { useToast } from '../components/ToastContext'
import { OrchestrationGraph } from '../components/FlowGraph'
import StatusBadge,{statusTone} from '../components/StatusBadge'
import {envLabel,runStatus,fmtDate,runStepStatus,deploymentStatus} from '../utils/format'

export default function AutomationRunDetailPage(){
 const {id}=useParams();const nav=useNavigate();const {t,pick,lang,localize}=useI18n();const toast=useToast();const {data:r,loading,reload}=useApiData(`/api/automation/runs/${id}`,{poll:2500});const [busy,setBusy]=useState(false)
 if(loading&&!r)return <div className="loading">{t('loading')}</div>;if(!r)return null
 const act=async a=>{setBusy(true);try{await api(`/api/automation/runs/${id}/${a}`,{method:'POST'});await reload();toast.push(t('operationSuccess'))}catch(e){toast.push(t('operationFailed'),'red')}finally{setBusy(false)}}
 const current=r.steps?.find(s=>s.status==='RUNNING')
 const terminal=['SUCCEEDED','FAILED','ROLLED_BACK'].includes(r.status)||r.progress>=100
 return <>
  <div className="detail-top"><button className="back-button" onClick={()=>nav(-1)}><ArrowLeft size={16}/>{t('back')}</button><div className="detail-actions">{r.taskId&&<button className={terminal?'btn primary next-action':'btn'} onClick={()=>nav(`/tasks/${r.taskId}`)}><ExternalLink size={15}/>{terminal?t('returnToTask'):t('remediationTask')}</button>}{!r.taskId&&r.deploymentId&&terminal&&<button className="btn primary next-action" onClick={()=>nav('/automation/batch')}><ExternalLink size={15}/>{t('returnToBatchPatch')}</button>}{r.status==='RUNNING'&&<button className="btn" disabled={busy} onClick={()=>act('pause')}><Pause size={15}/>{t('pause')}</button>}{r.status==='PAUSED'&&<button className="btn primary next-action" disabled={busy} onClick={()=>act('resume')}><Play size={15}/>{t('resume')}</button>}{r.templateCode!=='PATCH-RETEST'&&['RUNNING','PAUSED','FAILED'].includes(r.status)&&<button className="btn danger" disabled={busy} onClick={()=>act('rollback')}><RotateCcw size={15}/>{t('rollback')}</button>}</div></div>
  <section className="detail-hero automation-hero"><div><div className="eyebrow"><StatusBadge tone={statusTone(r.status)}>{runStatus(t,r.status)}</StatusBadge><StatusBadge tone="purple">{envLabel(t,r.environment)}</StatusBadge>{r.templateCode==='PATCH-RETEST'&&<StatusBadge tone="ok">{t('retestOnly')}</StatusBadge>}</div><h1>{r.runNo}</h1><h2>{pick(r,'templateNameZh','templateNameEn')} · {r.templateCode==='PATCH-RETEST'?t('retestOnly'):r.ring}</h2></div><div className="run-progress-summary"><div><strong>{r.progress}%</strong><span>{current?pick(current,'nameZh','nameEn'):runStatus(t,r.status)}</span></div><div className="run-progress-track"><i style={{width:`${r.progress}%`}}/></div></div></section>
  <div className="detail-grid"><section className="panel span-2"><div className="panel-head"><h2>{t('flowChart')}</h2><span className="live-indicator"><i/>{t('autoRefresh')}</span></div><div className="panel-body flow-wrap"><OrchestrationGraph steps={r.steps}/></div></section><section className="panel span-2"><div className="panel-head"><h2>{t('targetAssets')}</h2><span className="toolbar-count">{r.targets?.length||0}</span></div><div className="target-execution-list">{r.targets?.map(target=><div className="target-execution-row" key={target.id}><div className="target-icon"><Server size={16}/></div><div className="target-copy"><b>{localize(target.assetName)}</b><small>{target.batchNo?`${t('batch')} ${target.batchNo} · `:''}{target.assetCode} · {envLabel(t,target.environment)} · {localize(target.message)||'—'}</small></div><StatusBadge tone={statusTone(target.status)}>{deploymentStatus(t,target.status)}</StatusBadge><div className="progress-cell"><div className="progress"><i style={{width:`${target.progress}%`}}/></div><small>{target.progress}%</small></div></div>)}</div></section><section className="panel"><div className="kv-grid"><div><span>{t('environment')}</span><b>{envLabel(t,r.environment)}</b></div><div><span>{t('ring')}</span><b>{localize(r.ring)}</b></div><div><span>{t('startedAt')}</span><b>{fmtDate(r.startedAt,lang)}</b></div><div><span>{t('completedAt')}</span><b>{fmtDate(r.completedAt,lang)}</b></div></div></section><section className="panel"><div className="panel-head"><h2>{t('executionDetail')}</h2></div><div className="step-log">{r.steps?.map(s=><div className="step-log-row" key={s.id}><span className={`step-dot dot-${String(s.status).toLowerCase()}`}/><div><b>{pick(s,'nameZh','nameEn')}</b><small>{runStepStatus(t,s.status)} · {lang==='zh'?s.messageZh:s.messageEn}</small></div><time>{fmtDate(s.completedAt||s.startedAt,lang)}</time></div>)}</div></section></div>
 </>
}
