import React from 'react'
import { ArrowLeft, ExternalLink } from 'lucide-react'
import { useNavigate,useParams } from 'react-router-dom'
import { useApiData } from '../utils/useApiData'
import { useI18n } from '../contexts/I18nContext'
import StatusBadge,{statusTone} from '../components/StatusBadge'
import {changeStatus,fmtDate} from '../utils/format'

export default function ChangeOrderDetailPage(){
 const {id}=useParams();const nav=useNavigate();const {t,lang}=useI18n();const {data:x,loading}=useApiData(`/api/work-orders/changes/${id}`,{poll:10000});if(loading&&!x)return <div className="loading">{t('loading')}</div>;if(!x)return null
 return <><div className="detail-top"><button className="back-button" onClick={()=>nav(-1)}><ArrowLeft size={16}/>{t('back')}</button><div className="detail-actions"><button className="btn" onClick={()=>nav(`/work-orders/incidents/${x.incidentId}`)}><ExternalLink size={15}/>{t('securityIncident')}</button>{x.remediationTaskId&&<button className="btn" onClick={()=>nav(`/tasks/${x.remediationTaskId}`)}><ExternalLink size={15}/>{t('remediationTask')}</button>}{x.approvalId&&<button className="btn" onClick={()=>nav(`/approvals/${x.approvalId}`)}><ExternalLink size={15}/>{t('linkedApproval')}</button>}{x.latestRunId&&<button className="btn primary" onClick={()=>nav(`/automation/runs/${x.latestRunId}`)}><ExternalLink size={15}/>{t('linkedRun')}</button>}</div></div><section className="detail-hero"><div><div className="eyebrow"><StatusBadge tone={x.changeType==='EMERGENCY'?'critical':x.changeType==='MAJOR'?'high':'purple'}>{t(x.changeType)}</StatusBadge><StatusBadge tone={statusTone(x.status)}>{changeStatus(t,x.status)}</StatusBadge></div><h1>{x.changeNo}</h1><h2>{x.summary}</h2></div></section><div className="detail-grid"><section className="panel span-2"><div className="kv-grid three"><button className="kv-link" onClick={()=>nav(`/work-orders/incidents/${x.incidentId}`)}><span>{t('triggerSource')}</span><b>{x.incidentNo} <ExternalLink size={11}/></b></button><div><span>{t('cve')}</span><b>{x.cveId}</b></div><div><span>{t('asset')}</span><b>{x.assetName}</b></div><div><span>{t('businessService')}</span><b>{x.businessService}</b></div><div><span>{t('patch')}</span><b>{x.patchCode||'—'}</b></div><div><span>{t('approvalNo')}</span><b>{x.approvalNo||'—'}</b></div><div><span>{t('maintenanceStart')}</span><b>{fmtDate(x.maintenanceStart,lang)}</b></div><div><span>{t('maintenanceEnd')}</span><b>{fmtDate(x.maintenanceEnd,lang)}</b></div><div><span>{t('externalChange')}</span><b>{x.externalChangeNo||'—'}</b></div><div><span>{t('syncStatus')}</span><b>{x.syncStatus}</b></div></div></section>{[['riskAssessment',x.riskAssessment],['implementationPlan',x.implementationPlan],['rollbackPlan',x.rollbackPlan]].map(([key,value])=><section className="panel" key={key}><div className="panel-head"><h2>{t(key)}</h2></div><div className="panel-body"><p className="text-block">{value||'—'}</p></div></section>)}</div></>
}
