import React,{useMemo,useState} from 'react'
import {AlertTriangle,CheckCircle2,FileCheck2,Plus,RefreshCw,ShieldCheck,TimerReset} from 'lucide-react'
import {api} from '../api/client'
import {useApiData} from '../utils/useApiData'
import {useI18n} from '../contexts/I18nContext'
import {useAuth} from '../contexts/AuthContext'
import {useToast} from '../components/ToastContext'
import PageHeader from '../components/PageHeader'
import DataTable from '../components/DataTable'
import Modal from '../components/Modal'
import StatusBadge,{statusTone} from '../components/StatusBadge'

const emptyLifecycle={productName:'',versionPattern:'',status:'SUPPORTED',endOfSupportDate:'',endOfLifeDate:'',vendorNoticeUrl:'',replacementPlan:'',ownerName:''}
const emptyRegulatory={securityIncidentId:'',reportable:true,assessment:'',discoveredAt:''}

export default function CompliancePage(){
 const {t,lang}=useI18n(),{has}=useAuth(),toast=useToast();const [tab,setTab]=useState('alerts'),[busy,setBusy]=useState(false),[decision,setDecision]=useState(null),[comment,setComment]=useState(''),[lifecycleForm,setLifecycleForm]=useState(null),[regulatoryForm,setRegulatoryForm]=useState(null)
 const summary=useApiData('/api/compliance/summary');const alerts=useApiData('/api/compliance/alerts',{initial:[]});const exceptions=useApiData('/api/compliance/exceptions',{initial:[]});const lifecycle=useApiData('/api/compliance/lifecycle',{initial:[]});const regulatory=useApiData('/api/compliance/regulatory-cases',{initial:[]});const risk=useApiData('/api/compliance/risk-overrides',{initial:[]});const integrity=useApiData('/api/compliance/audit-integrity')
 const reloadAll=()=>Promise.all([summary.reload(),alerts.reload(),exceptions.reload(),lifecycle.reload(),regulatory.reload(),risk.reload(),integrity.reload()])
 const act=async(path,body={})=>{setBusy(true);try{await api(path,{method:'POST',body});await reloadAll();toast.push(t('operationSuccess'));setDecision(null);setComment('')}catch(e){toast.push(e.message||t('operationFailed'),'red')}finally{setBusy(false)}}
 const decide=()=>decision&&act(`/api/compliance/${decision.kind}/${decision.id}/${decision.action}`,{comment})
 const saveLifecycle=async()=>{setBusy(true);try{const id=lifecycleForm.id;await api(`/api/compliance/lifecycle${id?'/'+id:''}`,{method:id?'PUT':'POST',body:lifecycleForm});await Promise.all([lifecycle.reload(),summary.reload()]);setLifecycleForm(null);toast.push(t('operationSuccess'))}catch(e){toast.push(e.message||t('operationFailed'),'red')}finally{setBusy(false)}}
 const saveRegulatory=async()=>{setBusy(true);try{await api('/api/compliance/regulatory-cases',{method:'POST',body:{...regulatoryForm,securityIncidentId:Number(regulatoryForm.securityIncidentId)}});await Promise.all([regulatory.reload(),summary.reload(),alerts.reload()]);setRegulatoryForm(null);toast.push(t('operationSuccess'))}catch(e){toast.push(e.message||t('operationFailed'),'red')}finally{setBusy(false)}}
 const data=summary.data||{};const tabs=[['alerts',t('controlAlerts'),data.openAlerts],['exceptions',t('exceptionRegister'),data.pendingExceptions],['risk',t('riskReviews'),data.pendingRiskOverrides],['lifecycle',t('softwareLifecycle'),data.lifecycleRisks],['regulatory',t('regulatoryCases'),data.openRegulatoryCases]]
 const chain=integrity.data||{};const chainVerified=chain.status==='VERIFIED',chainFailed=chain.status==='FAILED'
 const badge=v=><StatusBadge tone={statusTone(v)}>{t(`compliance_${v}`)}</StatusBadge>
 const decisionButton=(kind,row,action,label)=>row.canApprove&&<button className={`btn ${action==='approve'?'primary':''}`} onClick={e=>{e.stopPropagation();setDecision({kind,id:row.id,action,label})}}>{label}</button>
 const columns=useMemo(()=>({
  alerts:[{key:'severity',label:t('severity'),render:r=><StatusBadge tone={r.severity==='CRITICAL'?'red':r.severity==='HIGH'?'warn':'gray'}>{r.severity}</StatusBadge>},{key:'message',label:t('message'),render:r=>lang==='zh'?r.messageZh:r.messageEn},{key:'dueAt',label:t('dueDate')},{key:'action',label:t('action'),render:r=>r.status==='OPEN'&&has('COMPLIANCE_MANAGE')?<button className="btn" onClick={()=>act(`/api/compliance/alerts/${r.id}/acknowledge`)}>{t('acknowledge')}</button>:badge(r.status)}],
  exceptions:[{key:'requestNo',label:t('requestNo')},{key:'cveId',label:'CVE'},{key:'assetName',label:t('asset')},{key:'requesterName',label:t('requestedBy')},{key:'expiresAt',label:t('expiresAt')},{key:'status',label:t('status'),render:r=>badge(r.status)},{key:'action',label:t('action'),render:r=><div className="row-actions">{decisionButton('exceptions',r,'approve',t('approve'))}{decisionButton('exceptions',r,'reject',t('reject'))}</div>}],
  risk:[{key:'requestNo',label:t('requestNo')},{key:'cveId',label:'CVE'},{key:'assetName',label:t('asset')},{key:'currentScore',label:t('currentRisk')},{key:'requestedScore',label:t('requestedRisk')},{key:'reason',label:t('reason')},{key:'status',label:t('status'),render:r=>badge(r.status)},{key:'action',label:t('action'),render:r=><div className="row-actions">{decisionButton('risk-overrides',r,'approve',t('approve'))}{decisionButton('risk-overrides',r,'reject',t('reject'))}</div>}],
  lifecycle:[{key:'productName',label:t('product')},{key:'versionPattern',label:t('version')},{key:'status',label:t('lifecycleStatus'),render:r=>badge(r.status)},{key:'endOfSupportDate',label:'EOS'},{key:'endOfLifeDate',label:'EOL'},{key:'affectedAssets',label:t('affectedAssets')},{key:'ownerName',label:t('owner')},{key:'action',label:t('action'),render:r=>has('LIFECYCLE_MANAGE')||has('COMPLIANCE_MANAGE')?<button className="btn" onClick={()=>setLifecycleForm({...r})}>{t('edit')}</button>:null}],
  regulatory:[{key:'caseNo',label:t('caseNo')},{key:'incidentNo',label:t('incidentNo')},{key:'reportable',label:t('reportable'),render:r=>r.reportable?t('yes'):t('no')},{key:'noticeDueAt',label:t('noticeDue')},{key:'rcaDueAt',label:t('rcaDue')},{key:'status',label:t('status'),render:r=>badge(r.status)}]
 }),[t,lang,has])
 const rows={alerts:alerts.data||[],exceptions:exceptions.data||[],risk:risk.data||[],lifecycle:lifecycle.data||[],regulatory:regulatory.data||[]}[tab]
 return <><PageHeader title={t('complianceCenter')}><button className="btn" onClick={reloadAll}><RefreshCw size={15}/>{t('refresh')}</button>{tab==='lifecycle'&&(has('LIFECYCLE_MANAGE')||has('COMPLIANCE_MANAGE'))&&<button className="btn primary" onClick={()=>setLifecycleForm({...emptyLifecycle})}><Plus size={15}/>{t('newLifecycle')}</button>}{tab==='regulatory'&&(has('REGULATORY_MANAGE')||has('COMPLIANCE_MANAGE'))&&<button className="btn primary" onClick={()=>setRegulatoryForm({...emptyRegulatory})}><Plus size={15}/>{t('newRegulatoryCase')}</button>}</PageHeader>
 <div className="compliance-summary"><div><AlertTriangle/><span>{t('openAlerts')}</span><b>{data.openAlerts??0}</b></div><div><FileCheck2/><span>{t('pendingExceptions')}</span><b>{data.pendingExceptions??0}</b></div><div><TimerReset/><span>{t('lifecycleRisks')}</span><b>{data.lifecycleRisks??0}</b></div><div className={data.auditIntegrity==='FAILED'?'summary-failed':''}><ShieldCheck/><span>{t('auditIntegrity')}</span><b className="summary-word">{data.auditIntegrity==='VERIFIED'?t('auditVerified'):data.auditIntegrity==='FAILED'?t('auditFailed'):'—'}</b></div></div>
 <div className="tabs compliance-tabs">{tabs.map(([key,label,count])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}<span>{count??0}</span></button>)}</div><DataTable columns={columns[tab]} rows={rows} pageSize={20}/>
 <div className={`integrity-foot ${chainVerified?'verified':chainFailed?'failed':'pending'}`}>{chainFailed?<AlertTriangle size={17}/>:<CheckCircle2 size={17}/>}<div className="integrity-copy"><span>{t('auditChainStatus')}</span><b>{chainVerified?t('auditVerified'):chainFailed?t('auditFailed'):'—'}</b></div><div className="integrity-meta"><span>{t('auditVerifiedCount',chain.verifiedEvents??0,chain.totalEvents??0)}</span>{chainFailed&&chain.firstInvalidEventId&&<strong>{t('auditFirstInvalid',chain.firstInvalidEventId)}</strong>}</div></div>
 <Modal open={!!decision} title={decision?.label} onClose={()=>setDecision(null)} footer={<><button className="btn" onClick={()=>setDecision(null)}>{t('cancel')}</button><button className="btn primary" disabled={busy||!comment.trim()} onClick={decide}>{t('confirm')}</button></>}><label className="form-field"><span>{t('decisionComment')}</span><textarea rows="5" value={comment} onChange={e=>setComment(e.target.value)}/></label></Modal>
 <Modal open={!!lifecycleForm} title={lifecycleForm?.id?t('editLifecycle'):t('newLifecycle')} onClose={()=>setLifecycleForm(null)} footer={<><button className="btn" onClick={()=>setLifecycleForm(null)}>{t('cancel')}</button><button className="btn primary" disabled={busy||!lifecycleForm?.productName} onClick={saveLifecycle}>{t('save')}</button></>}><div className="form-grid">{[['productName',t('product')],['versionPattern',t('version')],['endOfSupportDate','EOS'],['endOfLifeDate','EOL'],['ownerName',t('owner')],['vendorNoticeUrl',t('vendorAdvisory')]].map(([key,label])=><label className="form-field" key={key}><span>{label}</span><input type={key.includes('Date')?'date':'text'} value={lifecycleForm?.[key]||''} onChange={e=>setLifecycleForm({...lifecycleForm,[key]:e.target.value})}/></label>)}<label className="form-field"><span>{t('lifecycleStatus')}</span><select value={lifecycleForm?.status||'SUPPORTED'} onChange={e=>setLifecycleForm({...lifecycleForm,status:e.target.value})}>{['SUPPORTED','EXTENDED_SUPPORT','EOS','EOL'].map(x=><option key={x}>{x}</option>)}</select></label><label className="form-field full"><span>{t('replacementPlan')}</span><textarea rows="4" value={lifecycleForm?.replacementPlan||''} onChange={e=>setLifecycleForm({...lifecycleForm,replacementPlan:e.target.value})}/></label></div></Modal>
 <Modal open={!!regulatoryForm} title={t('newRegulatoryCase')} onClose={()=>setRegulatoryForm(null)} footer={<><button className="btn" onClick={()=>setRegulatoryForm(null)}>{t('cancel')}</button><button className="btn primary" disabled={busy||!regulatoryForm?.securityIncidentId||!regulatoryForm?.assessment} onClick={saveRegulatory}>{t('save')}</button></>}><div className="form-grid"><label className="form-field"><span>{t('securityIncidentId')}</span><input type="number" value={regulatoryForm?.securityIncidentId||''} onChange={e=>setRegulatoryForm({...regulatoryForm,securityIncidentId:e.target.value})}/></label><label className="form-field"><span>{t('reportable')}</span><select value={regulatoryForm?.reportable?'yes':'no'} onChange={e=>setRegulatoryForm({...regulatoryForm,reportable:e.target.value==='yes'})}><option value="yes">{t('yes')}</option><option value="no">{t('no')}</option></select></label><label className="form-field full"><span>{t('assessment')}</span><textarea rows="5" value={regulatoryForm?.assessment||''} onChange={e=>setRegulatoryForm({...regulatoryForm,assessment:e.target.value})}/></label></div></Modal>
 </>
}
