import React from 'react'
import { useNavigate } from 'react-router-dom'
import { ShieldAlert, AlertTriangle, ClipboardCheck, ScanSearch, Workflow, Gauge } from 'lucide-react'
import { useApiData } from '../utils/useApiData'
import { useI18n } from '../contexts/I18nContext'
import PageHeader from '../components/PageHeader'
import StatusBadge,{severityTone,statusTone} from '../components/StatusBadge'
import { envLabel,severityLabel,runStatus } from '../utils/format'

export default function DashboardPage(){const {t,pick}=useI18n();const nav=useNavigate();const {data:d,loading}=useApiData('/api/dashboard',{poll:20000});if(loading&&!d)return <div className="loading">{t('loading')}</div>;const metrics=[['openCritical',d?.openCritical,ShieldAlert,'critical','/vulnerabilities/findings?severity=CRITICAL'],['openHigh',d?.openHigh,AlertTriangle,'high','/vulnerabilities/findings?severity=HIGH'],['pendingApprovals',d?.pendingApprovals,ClipboardCheck,'purple','/approvals'],['runningScans',d?.runningScans,ScanSearch,'blue','/scans'],['runningAutomations',d?.runningAutomations,Workflow,'purple','/automation'],['patchCompliance',`${d?.patchCompliance??0}%`,Gauge,'ok','/reports']];return <><PageHeader title={t('dashboard')}/><div className="metric-grid">{metrics.map(([k,v,Icon,tone,to])=><button className="metric-card" key={k} onClick={()=>nav(to)}><div className={`metric-icon tone-${tone}`}><Icon size={19}/></div><div><span>{t(k)}</span><b>{v??0}</b></div></button>)}</div><div className="dashboard-grid"><section className="panel span-2"><div className="panel-head"><h2>{t('topFindings')}</h2></div><div className="compact-list">{d?.topFindings?.map(f=><button className="compact-row" key={f.id} onClick={()=>nav(`/vulnerabilities/findings/${f.id}`)}><div className="compact-main"><b>{f.cveId} · {pick(f)}</b><span>{f.assetName} · {f.businessService}</span></div><StatusBadge tone={severityTone(f.severity)}>{severityLabel(t,f.severity)}</StatusBadge><strong>{f.riskScore}</strong></button>)}</div></section><section className="panel"><div className="panel-head"><h2>{t('recentScans')}</h2></div><div className="compact-list">{d?.recentScans?.map(s=><button className="compact-row two" key={s.id} onClick={()=>nav('/scans')}><div className="compact-main"><b>{s.name}</b><span>{s.jobNo}</span></div><StatusBadge tone={statusTone(s.status)}>{t(String(s.status).toLowerCase())}</StatusBadge></button>)}</div></section><section className="panel span-3"><div className="panel-head"><h2>{t('recentRuns')}</h2></div><div className="run-list">{d?.recentRuns?.map(r=><button className="run-row" key={r.id} onClick={()=>nav(`/automation/runs/${r.id}`)}><div><b>{r.runNo}</b><span>{pick(r,'templateNameZh','templateNameEn')}</span></div><span>{envLabel(t,r.environment)}</span><span>{r.ring}</span><div className="progress-cell"><div className="progress"><i style={{width:`${r.progress}%`}}/></div><small>{r.progress}%</small></div><StatusBadge tone={statusTone(r.status)}>{runStatus(t,r.status)}</StatusBadge></button>)}</div></section></div></>}
