import React,{useState} from 'react'
import { ArrowLeft, CheckCircle2, Ban, ShieldCheck, ExternalLink, BookOpenText, Calculator } from 'lucide-react'
import { useNavigate,useParams } from 'react-router-dom'
import { useApiData } from '../utils/useApiData'
import { api } from '../api/client'
import { useI18n } from '../contexts/I18nContext'
import { useToast } from '../components/ToastContext'
import { useAuth } from '../contexts/AuthContext'
import Modal from '../components/Modal'
import StatusBadge,{severityTone,statusTone} from '../components/StatusBadge'
import {envLabel,findingStatus,severityLabel,fmtDate} from '../utils/format'

function dateAfter(days){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}

export default function FindingDetailPage(){
 const {id}=useParams();const nav=useNavigate();const {t,pick,lang,localize}=useI18n();const toast=useToast();const {has}=useAuth()
 const {data:f,loading,reload}=useApiData(`/api/vulnerabilities/findings/${id}`)
 const [tab,setTab]=useState('overview'),[fp,setFp]=useState(false),[exempt,setExempt]=useState(false),[riskModal,setRiskModal]=useState(false),[reason,setReason]=useState(''),[expiresAt,setExpiresAt]=useState(()=>dateAfter(30)),[compensatingControl,setCompensatingControl]=useState(''),[residualRisk,setResidualRisk]=useState(''),[requestedScore,setRequestedScore]=useState(''),[busy,setBusy]=useState(false)
 if(loading&&!f)return <div className="loading">{t('loading')}</div>;if(!f)return null
 const pendingConfirmation=['NEW','REOPENED'].includes(f.status)||(f.status==='CONFIRMED'&&!f.securityIncidentId)
 const confirm=async()=>{setBusy(true);try{const confirmed=await api(`/api/vulnerabilities/findings/${id}/confirm`,{method:'POST',body:{}});toast.push(t('findingConfirmedAndIncidentCreated'));if(confirmed?.securityIncidentId)nav(`/work-orders/incidents/${confirmed.securityIncidentId}`,{replace:true});else await reload()}catch(e){toast.push(e.message||t('operationFailed'),'red')}finally{setBusy(false)}}
 const falsePositive=async()=>{setBusy(true);try{await api(`/api/vulnerabilities/findings/${id}/false-positive`,{method:'POST',body:{reason}});setFp(false);setReason('');await reload();toast.push(t('operationSuccess'))}catch(e){toast.push(t('operationFailed'),'red')}finally{setBusy(false)}}
 const submitExemption=async()=>{setBusy(true);try{await api(`/api/vulnerabilities/findings/${id}/exempt`,{method:'POST',body:{reason,expiresAt,compensatingControl,residualRisk}});setExempt(false);setReason('');setCompensatingControl('');setResidualRisk('');await reload();toast.push(t('exceptionSubmitted'))}catch(e){toast.push(e.message||t('operationFailed'),'red')}finally{setBusy(false)}}
 const submitRisk=async()=>{setBusy(true);try{await api('/api/compliance/risk-overrides',{method:'POST',body:{findingId:Number(id),requestedScore:Number(requestedScore),reason}});setRiskModal(false);setReason('');setRequestedScore('');toast.push(t('riskReviewSubmitted'))}catch(e){toast.push(e.message||t('operationFailed'),'red')}finally{setBusy(false)}}
 const evidenceLabels={zh:{evidence_id:'证据编号',scan_job:'扫描任务',scanner:'扫描器',policy:'扫描策略',target:'扫描目标',asset_ci:'资产编号',collected_at:'采集时间',evidence_sha256:'证据摘要'},en:{evidence_id:'Evidence ID',scan_job:'Scan Job',scanner:'Scanner',policy:'Policy',target:'Target',asset_ci:'Asset Code',collected_at:'Collected At',evidence_sha256:'Evidence Digest'}}
 const evidenceRows=(f.evidence||'').split('\n').slice(1).map(line=>{const index=line.indexOf(':');return index>0?[line.slice(0,index).trim(),line.slice(index+1).trim()]:null}).filter(row=>row&&Object.hasOwn(evidenceLabels.zh,row[0]))
 const proof=f.evidenceProof
 let riskFactors={};try{riskFactors=JSON.parse(f.riskFactors||'{}')}catch{}
 const reasonLabels={KNOWN_EXPLOITED:t('reasonKnownExploited'),CRITICAL_SEVERITY:t('reasonCritical'),INTERNET_EXPOSED:t('reasonInternetExposed'),CORE_ASSET:t('reasonCoreAsset'),EXCEPTION_ACTIVE:t('reasonException')}
 return <>
  <div className="detail-top"><button className="back-button" onClick={()=>nav(-1)}><ArrowLeft size={16}/>{t('back')}</button><div className="detail-actions" role="group" aria-label={t('availableActions')}>
   <button className="btn" onClick={()=>nav(`/vulnerabilities/library/${encodeURIComponent(f.cveId)}`)}><BookOpenText size={15}/>{t('vulnerabilityLibraryDetail')}</button>
   {f.securityIncidentId&&<button className={!f.remediationTaskId&&f.status==='CONFIRMED'?'btn primary next-action':'btn'} onClick={()=>nav(`/work-orders/incidents/${f.securityIncidentId}`)}><ExternalLink size={15}/>{t('securityIncident')}</button>}{f.remediationTaskId&&<button className={f.status==='IN_REMEDIATION'?'btn primary next-action':'btn'} onClick={()=>nav(`/tasks/${f.remediationTaskId}`)}><ExternalLink size={15}/>{t('remediationTask')}</button>}
   {pendingConfirmation&&<>{(has('VULNERABILITY_FALSE_POSITIVE')||has('VULNERABILITY_MANAGE'))&&<button className="btn" onClick={()=>{setReason('');setFp(true)}}><Ban size={15}/>{t('markFalsePositive')}</button>}{(has('VULNERABILITY_EXEMPT')||has('VULNERABILITY_MANAGE'))&&<button className="btn" onClick={()=>{setReason('');setExempt(true)}}><ShieldCheck size={15}/>{t('exemptFinding')}</button>}{(has('VULNERABILITY_CONFIRM')||has('VULNERABILITY_MANAGE'))&&<button className="btn primary next-action" onClick={confirm} disabled={busy}><CheckCircle2 size={15}/>{t('confirmFinding')}</button>}</>}
  </div></div>
  <section className="detail-hero"><div><div className="eyebrow"><StatusBadge tone={severityTone(f.severity)}>{severityLabel(t,f.severity)}</StatusBadge><StatusBadge tone={statusTone(f.status)}>{findingStatus(t,f.status)}</StatusBadge>{f.exemptionStatus&&<StatusBadge tone={f.exemptionStatus==='PENDING'?'warn':'gray'}>{t(`compliance_${f.exemptionStatus}`)}</StatusBadge>}{f.kev&&<StatusBadge tone="critical">CISA KEV</StatusBadge>}</div><h1>{f.cveId}</h1><h2>{pick(f)}</h2></div><div className="score-box"><b>{f.riskScore}</b><span>{t('riskScore')}</span></div></section>
  <div className="tabs vulnerability-tabs finding-detail-tabs">{[['overview','findingOverview'],['evidence','evidence'],['asset','assetAndImpact'],['remediation','remediationRecord']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{t(label)}</button>)}</div>
  <div className="detail-grid tabbed-detail finding-tab-content">
   {tab==='asset'&&<section className="panel span-2"><div className="kv-grid"><div><span>{t('asset')}</span><b>{localize(f.assetName)}</b></div><div><span>{t('assetCode')}</span><b>{f.assetCode}</b></div><div><span>{t('environment')}</span><b>{envLabel(t,f.environment)}</b></div><div><span>{t('businessService')}</span><b>{localize(f.businessService)}</b></div><div><span>{t('owner')}</span><b>{localize(f.ownerName)||'—'}</b></div><div><span>{t('scanSource')}</span><b>{f.scanJobNo||'—'}</b></div><div><span>{t('criticality')}</span><b>{f.assetCriticality}</b></div><div><span>{t('internetExposure')}</span><b>{f.internetExposed?t('yes'):t('no')}</b></div><div><span>{t('firstSeen')}</span><b>{fmtDate(f.firstSeenAt,lang)}</b></div><div><span>{t('lastSeen')}</span><b>{fmtDate(f.lastSeenAt,lang)}</b></div>{f.status==='EXEMPTED'&&<><div><span>{t('exemptionExpires')}</span><b>{fmtDate(f.exemptionExpiresAt,lang)}</b></div><div><span>{t('exemptionReason')}</span><b>{localize(f.exemptionReason)||'—'}</b></div><div><span>{t('compensatingControl')}</span><b>{localize(f.compensatingControl)||'—'}</b></div><div><span>{t('residualRisk')}</span><b>{localize(f.residualRisk)||'—'}</b></div><div><span>{t('exemptionApprover')}</span><b>{localize(f.exemptionApprovedBy)||'—'}</b></div><div><span>{t('approvedAt')}</span><b>{fmtDate(f.exemptionApprovedAt,lang)}</b></div></>}</div></section>}
   {tab==='remediation'&&<><section className="panel span-2"><div className="panel-head"><h2>{t('patchAvailable')}</h2></div><div className="patch-candidate-grid compact">{f.patchCandidates?.length?f.patchCandidates.map(p=><button className="patch-candidate" key={p.id} onClick={()=>nav(`/patches/${p.id}`)}><div><b>{p.patchId}</b><span>{pick(p,'titleZh','titleEn')}</span></div><ExternalLink size={13}/></button>):<span className="muted panel-body">—</span>}</div></section><section className="panel span-2"><div className="kv-grid"><div><span>{t('securityIncident')}</span><b>{f.securityIncidentId||t('notCreated')}</b></div><div><span>{t('remediationTask')}</span><b>{f.remediationTaskId||t('notCreated')}</b></div><div><span>{t('status')}</span><b>{findingStatus(t,f.status)}</b></div><div><span>{t('owner')}</span><b>{localize(f.ownerName)||'—'}</b></div></div></section></>}
   {tab==='overview'&&<><section className="panel span-2"><div className="panel-head"><h2>{t('priorityBasis')}</h2></div><div className="priority-reasons">{f.priorityReasons?.map(reason=><StatusBadge key={reason} tone={reason==='KNOWN_EXPLOITED'||reason==='INTERNET_EXPOSED'?'critical':'purple'}>{reasonLabels[reason]||reason}</StatusBadge>)}</div></section><section className="panel span-2"><div className="panel-head"><h2>{t('riskCalculation')}</h2>{(has('RISK_OVERRIDE_REQUEST')||has('VULNERABILITY_MANAGE'))&&<button className="btn" onClick={()=>{setReason('');setRequestedScore(String(f.riskScore??''));setRiskModal(true)}}><Calculator size={14}/>{t('requestRiskReview')}</button>}</div><div className="risk-factor-grid"><div><span>{t('formulaVersion')}</span><b>{f.riskFormulaVersion||'—'}</b></div><div><span>{t('baseRisk')}</span><b>{f.baseRiskScore??'—'}</b></div>{Object.entries(riskFactors).filter(([key])=>key!=='formulaVersion').map(([key,value])=><div key={key}><span>{t(`riskFactor_${key}`)}</span><b>{String(value)}</b></div>)}</div></section></>}
   {tab==='evidence'&&<section className="panel span-2"><div className="panel-head"><h2>{t('evidence')}</h2>{f.evidence?.includes('evidence_sha256:')&&<span className="evidence-trust">{t('evidenceIntegrity')}</span>}</div>
    <div className="evidence-record-grid">{evidenceRows.map(([key,value])=><div key={key} className={key==='evidence_sha256'?'wide':''}><span>{evidenceLabels[lang]?.[key]||key}</span><b className={key==='evidence_sha256'?'mono':''}>{value}</b></div>)}</div>
    {proof?<div className="evidence-proof"><div className="evidence-proof-summary"><div><span>{t('evidenceType')}</span><b>{proof.evidenceType==='PACKAGE_VERSION'?t('packageVersionComparison'):proof.evidenceType}</b></div><div><span>{t('evidenceSource')}</span><b className="mono">{proof.sourcePath||'—'}</b></div><div><span>{t('affectedCondition')}</span><b>{lang==='zh'?(proof.affectedConditionZh||proof.affectedConditionEn):(proof.affectedConditionEn||proof.affectedConditionZh)||'—'}</b></div><div><span>{t('fixedVersion')}</span><b>{proof.fixedVersion||'—'}</b></div><div><span>{t('scannerRule')}</span><b className="mono">{proof.scannerRuleId||'—'}</b></div><div><span>{t('decision')}</span><b>{proof.decision||'—'}</b></div></div><div className="evidence-command"><span>{t('collectionCommand')}</span><code>{proof.collectionCommand||'—'}</code></div><div className="evidence-code-head"><b>{t('rawEvidence')}</b><span>{proof.origin==='SCANNER_RAW'?t('evidenceRawNote'):t('evidenceDerivedNote')}</span></div><div className="evidence-code" role="table" aria-label={t('rawEvidence')}>{proof.lines?.map(line=><div className={line.highlighted?'evidence-code-line highlighted':'evidence-code-line'} key={`${line.lineNumber}-${line.content}`}><span className="line-number">{line.lineNumber}</span><code>{line.content}</code>{line.highlighted&&<strong>{lang==='zh'?line.annotationZh:line.annotationEn}</strong>}</div>)}</div></div>:<div className="panel-body muted">{t('noData')}</div>}
   </section>}</div>
  <Modal open={fp} title={t('confirmFalsePositive')} onClose={()=>setFp(false)} footer={<><button className="btn" onClick={()=>setFp(false)}>{t('cancel')}</button><button className="btn primary" disabled={!reason.trim()||busy} onClick={falsePositive}>{t('confirm')}</button></>}><label className="form-field"><span>{t('falsePositiveReason')}</span><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={4}/></label></Modal>
  <Modal open={exempt} title={t('confirmExemption')} onClose={()=>setExempt(false)} footer={<><button className="btn" onClick={()=>setExempt(false)}>{t('cancel')}</button><button className="btn primary" disabled={!reason.trim()||!compensatingControl.trim()||!residualRisk.trim()||!expiresAt||busy} onClick={submitExemption}>{t('confirm')}</button></>}><div className="form-grid"><label className="form-field full"><span>{t('exemptionReason')} *</span><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3}/></label><label className="form-field full"><span>{t('compensatingControl')} *</span><textarea value={compensatingControl} onChange={e=>setCompensatingControl(e.target.value)} rows={3}/></label><label className="form-field full"><span>{t('residualRisk')} *</span><textarea value={residualRisk} onChange={e=>setResidualRisk(e.target.value)} rows={3}/></label><label className="form-field"><span>{t('exemptionExpires')}</span><input type="date" value={expiresAt} min={new Date().toISOString().slice(0,10)} onChange={e=>setExpiresAt(e.target.value)}/></label></div></Modal>
  <Modal open={riskModal} title={t('requestRiskReview')} onClose={()=>setRiskModal(false)} footer={<><button className="btn" onClick={()=>setRiskModal(false)}>{t('cancel')}</button><button className="btn primary" disabled={busy||requestedScore===''||Number(requestedScore)<0||Number(requestedScore)>10||!reason.trim()} onClick={submitRisk}>{t('submit')}</button></>}><div className="form-grid"><label className="form-field"><span>{t('requestedRisk')}</span><input type="number" min="0" max="10" step="0.1" value={requestedScore} onChange={e=>setRequestedScore(e.target.value)}/></label><label className="form-field full"><span>{t('reason')}</span><textarea rows="5" value={reason} onChange={e=>setReason(e.target.value)}/></label></div></Modal>
 </>
}
