import React,{useState} from 'react'
import { ArrowLeft, CheckCircle2, Ban, ShieldCheck, ExternalLink } from 'lucide-react'
import { useNavigate,useParams } from 'react-router-dom'
import { useApiData } from '../utils/useApiData'
import { api } from '../api/client'
import { useI18n } from '../contexts/I18nContext'
import { useToast } from '../components/ToastContext'
import Modal from '../components/Modal'
import StatusBadge,{severityTone,statusTone} from '../components/StatusBadge'
import {envLabel,findingStatus,severityLabel,fmtDate} from '../utils/format'

function dateAfter(days){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}

export default function FindingDetailPage(){
 const {id}=useParams();const nav=useNavigate();const {t,pick,lang,localize}=useI18n();const toast=useToast()
 const {data:f,loading,reload}=useApiData(`/api/vulnerabilities/findings/${id}`)
 const [fp,setFp]=useState(false),[exempt,setExempt]=useState(false),[reason,setReason]=useState(''),[expiresAt,setExpiresAt]=useState(()=>dateAfter(30)),[busy,setBusy]=useState(false)
 if(loading&&!f)return <div className="loading">{t('loading')}</div>;if(!f)return null
 const pendingConfirmation=['NEW','REOPENED'].includes(f.status)||(f.status==='CONFIRMED'&&!f.securityIncidentId)
 const confirm=async()=>{setBusy(true);try{const confirmed=await api(`/api/vulnerabilities/findings/${id}/confirm`,{method:'POST',body:{}});toast.push(t('findingConfirmedAndIncidentCreated'));if(confirmed?.securityIncidentId)nav(`/work-orders/incidents/${confirmed.securityIncidentId}`,{replace:true});else await reload()}catch(e){toast.push(e.message||t('operationFailed'),'red')}finally{setBusy(false)}}
 const falsePositive=async()=>{setBusy(true);try{await api(`/api/vulnerabilities/findings/${id}/false-positive`,{method:'POST',body:{reason}});setFp(false);setReason('');await reload();toast.push(t('operationSuccess'))}catch(e){toast.push(t('operationFailed'),'red')}finally{setBusy(false)}}
 const submitExemption=async()=>{setBusy(true);try{await api(`/api/vulnerabilities/findings/${id}/exempt`,{method:'POST',body:{reason,expiresAt}});setExempt(false);setReason('');await reload();toast.push(t('operationSuccess'))}catch(e){toast.push(t('operationFailed'),'red')}finally{setBusy(false)}}
 const evidenceLabels={zh:{evidence_id:'证据编号',scan_job:'扫描任务',scanner:'扫描器',policy:'扫描策略',target:'扫描目标',asset_ci:'CMDB 资产',transport:'采集通道',detection_rule:'检测规则',method:'检测方法',component:'组件',observed_version:'观测版本',installed_inventory:'软件清单',rule_result:'规则结果',service_state:'服务状态',confidence:'置信度',result:'扫描结果',collected_at:'采集时间',evidence_sha256:'证据摘要'},en:{evidence_id:'Evidence ID',scan_job:'Scan Job',scanner:'Scanner',policy:'Policy',target:'Target',asset_ci:'CMDB Asset',transport:'Collection Channel',detection_rule:'Detection Rule',method:'Method',component:'Component',observed_version:'Observed Version',installed_inventory:'Installed Inventory',rule_result:'Rule Result',service_state:'Service State',confidence:'Confidence',result:'Result',collected_at:'Collected At',evidence_sha256:'Evidence Digest'}}
 const evidenceRows=(f.evidence||'').split('\n').slice(1).map(line=>{const index=line.indexOf(':');return index>0?[line.slice(0,index).trim(),line.slice(index+1).trim()]:null}).filter(Boolean)
 const reasonLabels={KNOWN_EXPLOITED:t('reasonKnownExploited'),CRITICAL_SEVERITY:t('reasonCritical'),INTERNET_EXPOSED:t('reasonInternetExposed'),CORE_ASSET:t('reasonCoreAsset'),EXCEPTION_ACTIVE:t('reasonException')}
 return <>
  <div className="detail-top"><button className="back-button" onClick={()=>nav(-1)}><ArrowLeft size={16}/>{t('back')}</button><div className="detail-actions">
   {f.securityIncidentId&&<button className={!f.remediationTaskId&&f.status==='CONFIRMED'?'btn primary next-action':'btn'} onClick={()=>nav(`/work-orders/incidents/${f.securityIncidentId}`)}><ExternalLink size={15}/>{t('securityIncident')}</button>}{f.remediationTaskId&&<button className={f.status==='IN_REMEDIATION'?'btn primary next-action':'btn'} onClick={()=>nav(`/tasks/${f.remediationTaskId}`)}><ExternalLink size={15}/>{t('remediationTask')}</button>}
   {pendingConfirmation&&<><button className="btn" onClick={()=>{setReason('');setFp(true)}}><Ban size={15}/>{t('markFalsePositive')}</button><button className="btn" onClick={()=>{setReason('');setExempt(true)}}><ShieldCheck size={15}/>{t('exemptFinding')}</button><button className="btn primary next-action" onClick={confirm} disabled={busy}><CheckCircle2 size={15}/>{t('confirmFinding')}</button></>}
  </div></div>
  <section className="detail-hero"><div><div className="eyebrow"><StatusBadge tone={severityTone(f.severity)}>{severityLabel(t,f.severity)}</StatusBadge><StatusBadge tone={statusTone(f.status)}>{findingStatus(t,f.status)}</StatusBadge>{f.kev&&<StatusBadge tone="critical">CISA KEV</StatusBadge>}</div><h1>{f.cveId}</h1><h2>{pick(f)}</h2></div><div className="score-box"><b>{f.riskScore}</b><span>{t('riskScore')}</span></div></section>
  <div className="detail-grid"><section className="panel"><div className="kv-grid"><div><span>{t('asset')}</span><b>{localize(f.assetName)}</b></div><div><span>{t('assetCode')}</span><b>{f.assetCode}</b></div><div><span>{t('environment')}</span><b>{envLabel(t,f.environment)}</b></div><div><span>{t('businessService')}</span><b>{localize(f.businessService)}</b></div><div><span>{t('owner')}</span><b>{localize(f.ownerName)||'—'}</b></div><div><span>{t('scanSource')}</span><b>{f.scanJobNo||'—'}</b></div><div><span>{t('criticality')}</span><b>{f.assetCriticality}</b></div><div><span>{t('internetExposure')}</span><b>{f.internetExposed?t('yes'):t('no')}</b></div><div><span>{t('firstSeen')}</span><b>{fmtDate(f.firstSeenAt,lang)}</b></div><div><span>{t('lastSeen')}</span><b>{fmtDate(f.lastSeenAt,lang)}</b></div>{f.status==='EXEMPTED'&&<><div><span>{t('exemptionExpires')}</span><b>{fmtDate(f.exemptionExpiresAt,lang)}</b></div><div><span>{t('exemptionReason')}</span><b>{localize(f.exemptionReason)||'—'}</b></div></>}</div></section>
   <section className="panel"><div className="panel-head"><h2>{t('patchAvailable')}</h2></div><div className="patch-candidate-grid compact">{f.patchCandidates?.length?f.patchCandidates.map(p=><button className="patch-candidate" key={p.id} onClick={()=>nav(`/patches/${p.id}`)}><div><b>{p.patchId}</b><span>{pick(p,'titleZh','titleEn')}</span></div><ExternalLink size={13}/></button>):<span className="muted panel-body">—</span>}</div></section>
   <section className="panel span-2"><div className="panel-head"><h2>{t('priorityBasis')}</h2></div><div className="priority-reasons">{f.priorityReasons?.map(reason=><StatusBadge key={reason} tone={reason==='KNOWN_EXPLOITED'||reason==='INTERNET_EXPOSED'?'critical':'purple'}>{reasonLabels[reason]||reason}</StatusBadge>)}</div></section>
   <section className="panel span-2"><div className="panel-head"><h2>{t('evidence')}</h2>{f.evidence?.includes('evidence_sha256:')&&<span className="evidence-trust">{t('evidenceIntegrity')}</span>}</div><div className="evidence-record-grid">{evidenceRows.length?evidenceRows.map(([key,value])=><div key={key} className={key==='installed_inventory'||key==='rule_result'||key==='evidence_sha256'?'wide':''}><span>{evidenceLabels[lang]?.[key]||key}</span><b className={key==='evidence_sha256'?'mono':''}>{value}</b></div>):<span className="muted">{t('noData')}</span>}</div></section></div>
  <Modal open={fp} title={t('confirmFalsePositive')} onClose={()=>setFp(false)} footer={<><button className="btn" onClick={()=>setFp(false)}>{t('cancel')}</button><button className="btn primary" disabled={!reason.trim()||busy} onClick={falsePositive}>{t('confirm')}</button></>}><label className="form-field"><span>{t('falsePositiveReason')}</span><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={4}/></label></Modal>
  <Modal open={exempt} title={t('confirmExemption')} onClose={()=>setExempt(false)} footer={<><button className="btn" onClick={()=>setExempt(false)}>{t('cancel')}</button><button className="btn primary" disabled={!reason.trim()||!expiresAt||busy} onClick={submitExemption}>{t('confirm')}</button></>}><div className="form-grid"><label className="form-field full"><span>{t('exemptionReason')}</span><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={4}/></label><label className="form-field"><span>{t('exemptionExpires')}</span><input type="date" value={expiresAt} min={new Date().toISOString().slice(0,10)} onChange={e=>setExpiresAt(e.target.value)}/></label></div></Modal>
 </>
}
