import React,{useState} from 'react'
import {ArrowLeft,Copy,ShieldCheck,Smartphone} from 'lucide-react'
import {useNavigate} from 'react-router-dom'
import {useI18n} from '../contexts/I18nContext'
import {useAuth} from '../contexts/AuthContext'

export default function LoginPage(){
 const {t,lang,setLang}=useI18n(),{login}=useAuth(),nav=useNavigate()
 const [username,setUsername]=useState('admin'),[password,setPassword]=useState(''),[otp,setOtp]=useState(''),[challenge,setChallenge]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false)
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const data=await login(username,password,challenge?otp:null);if(data.mfaRequired){setChallenge(data);setOtp('');return}if(data.token)nav('/')}catch{setError(t(challenge?'mfaVerificationFailed':'loginFailed'))}finally{setBusy(false)}}
 const restart=()=>{setChallenge(null);setOtp('');setError('');setCopied(false)}
 const copyKey=async()=>{if(!challenge?.mfaSetupKey)return;await navigator.clipboard?.writeText(challenge.mfaSetupKey);setCopied(true)}
 return <div className="login-page"><div className="login-card"><div className="login-brand"><img src="/gazellio-logo.png" alt="ANOWX"/><button onClick={()=>setLang(lang==='zh'?'en':'zh')}>{lang==='zh'?t('switchToEnglish'):t('switchToChinese')}</button></div><div className="login-icon">{challenge?<Smartphone size={24}/>:<ShieldCheck size={25}/>}</div><h1>{challenge?t(challenge.mfaEnrollmentRequired?'mfaSetupTitle':'mfaVerifyTitle'):t('loginTitle')}</h1><form onSubmit={submit}>{!challenge?<><label>{t('username')}<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username"/></label><label>{t('password')}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label></>:<><div className="mfa-account"><span>{t('username')}</span><b>{username}</b></div>{challenge.mfaEnrollmentRequired&&<div className="mfa-setup"><p>{t('mfaSetupInstructions')}</p><div><code>{challenge.mfaSetupKey}</code><button type="button" onClick={copyKey} title={t('copy')}><Copy size={14}/></button></div>{copied&&<small>{t('copied')}</small>}</div>}<label>{t('verificationCode')}<input className="otp-input" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" maxLength="6" autoFocus placeholder="000000"/></label></>}{error&&<div className="form-error">{error}</div>}<button className="btn primary full" disabled={busy||challenge&&otp.length!==6}>{busy?'…':t(challenge?'verifyAndLogin':'login')}</button>{challenge&&<button className="login-back" type="button" onClick={restart}><ArrowLeft size={14}/>{t('backToLogin')}</button>}</form></div></div>
}
