import React,{useMemo,useState} from 'react'
import {CalendarDays,ChevronLeft,ChevronRight,Plus,Trash2} from 'lucide-react'
import {useNavigate} from 'react-router-dom'
import {api} from '../api/client'
import {useApiData} from '../utils/useApiData'
import {useI18n} from '../contexts/I18nContext'
import {useAuth} from '../contexts/AuthContext'
import {useToast} from '../components/ToastContext'
import PageHeader from '../components/PageHeader'
import Modal from '../components/Modal'

function monthKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`}
function moveMonth(key,amount){const [y,m]=key.split('-').map(Number);return monthKey(new Date(y,m-1+amount,1))}
function localInput(value){if(!value)return '';const d=new Date(value);const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function emptySchedule(){const start=new Date();start.setMinutes(0,0,0);start.setHours(start.getHours()+1);const end=new Date(start.getTime()+2*3600000);return {titleZh:'',titleEn:'',patchId:'',environment:'PROD',startAt:localInput(start),endAt:localInput(end),status:'PLANNED',notes:''}}

export default function PatchCalendarPage(){
 const {t,lang,localize}=useI18n(),{has}=useAuth(),toast=useToast(),nav=useNavigate();const [month,setMonth]=useState(monthKey(new Date())),[form,setForm]=useState(null),[busy,setBusy]=useState(false)
 const {data:events=[],loading,reload}=useApiData(`/api/patches/calendar?month=${month}`,{initial:[]});const {data:patches=[]}=useApiData('/api/patches',{initial:[]})
 const [year,mon]=month.split('-').map(Number);const first=new Date(year,mon-1,1);const count=new Date(year,mon,0).getDate();const offset=(first.getDay()+6)%7;const totalCells=Math.ceil((offset+count)/7)*7
 const days=useMemo(()=>[...Array(offset).fill(null),...Array.from({length:count},(_,i)=>i+1),...Array(totalCells-offset-count).fill(null)],[offset,count,totalCells])
 const segments=useMemo(()=>events.flatMap((event,eventIndex)=>{
  const start=new Date(event.date),end=event.endAt?new Date(event.endAt):start;const monthStart=new Date(year,mon-1,1),monthEnd=new Date(year,mon,0,23,59,59,999)
  if(Number.isNaN(start.valueOf())||end<monthStart||start>monthEnd)return []
  let from=start.getFullYear()===year&&start.getMonth()===mon-1?start.getDate():1;let to=end.getFullYear()===year&&end.getMonth()===mon-1?end.getDate():count;const out=[]
  while(from<=to){const index=offset+from-1;const week=Math.floor(index/7);const endOfWeek=Math.min(to,(week+1)*7-offset);const startColumn=index%7+1;const endColumn=(offset+endOfWeek-1)%7+2;out.push({...event,segmentId:`${event.eventId}-${from}`,gridColumn:`${startColumn} / ${endColumn}`,gridRow:week+1,segmentOffset:(eventIndex%3)*24});from=endOfWeek+1}
  return out
 }),[events,year,mon,count,offset])
 const locale=lang==='zh'?'zh-CN':'en-US';const title=new Intl.DateTimeFormat(locale,{year:'numeric',month:'long'}).format(first)
 const edit=async event=>{if(event.editable){try{const row=await api(`/api/patches/calendar/schedules/${event.scheduleId}`);setForm({...row,startAt:localInput(row.startAt),endAt:localInput(row.endAt)})}catch(e){toast.push(e.message,'red')}}else nav(event.changeOrderId?`/work-orders/changes/${event.changeOrderId}`:`/work-orders/incidents/${event.incidentId}`)}
 const save=async()=>{setBusy(true);try{const editing=!!form.id;await api(`/api/patches/calendar/schedules${editing?`/${form.id}`:''}`,{method:editing?'PUT':'POST',body:{...form,patchId:Number(form.patchId),startAt:new Date(form.startAt).toISOString(),endAt:new Date(form.endAt).toISOString()}});setForm(null);await reload();toast.push(t('scheduleSaved'))}catch(e){toast.push(e.message,'red')}finally{setBusy(false)}}
 const remove=async()=>{if(!window.confirm(t('confirmDeleteSchedule')))return;setBusy(true);try{await api(`/api/patches/calendar/schedules/${form.id}`,{method:'DELETE'});setForm(null);await reload();toast.push(t('operationSuccess'))}catch(e){toast.push(e.message,'red')}finally{setBusy(false)}}
 const weekdays=lang==='zh'?['一','二','三','四','五','六','日']:['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
 const eventTitle=event=>event.editable?(lang==='zh'?event.titleZh:event.titleEn):(event.patchCode||event.cveId)
 return <>
  <PageHeader title={t('patchCalendar')}><button className="btn" onClick={()=>setMonth(moveMonth(month,-1))}><ChevronLeft size={15}/></button><button className="btn calendar-month-label" onClick={()=>setMonth(monthKey(new Date()))}>{title}</button><button className="btn" onClick={()=>setMonth(moveMonth(month,1))}><ChevronRight size={15}/></button>{has('PATCH_SCHEDULE')&&<button className="btn primary" onClick={()=>setForm({...emptySchedule(),patchId:patches[0]?.id||''})}><Plus size={15}/>{t('newSchedule')}</button>}</PageHeader>
  <div className="calendar-legend"><span><i className="cal-dot p1"/>P1 · 3{t('days')}</span><span><i className="cal-dot p2"/>P2 · 7{t('days')}</span><span><i className="cal-dot p3"/>P3 · 30{t('days')}</span><span><i className="cal-dot p4"/>P4 · {t('cycle')}</span><span className="legend-spacer"/><span><i className="cal-outline overdue"/>{t('overdue')}</span><span><i className="cal-outline window"/>{t('maintenanceWindow')}</span><span><i className="cal-outline plan"/>{t('patchPlan')}</span></div>
  <div className="patch-calendar"><div className="calendar-weekdays">{weekdays.map(d=><div key={d}>{d}</div>)}</div><div className="calendar-grid">{days.map((day,index)=><div key={index} className={`calendar-day ${!day?'empty':''}`}><span className="day-number">{day||''}</span></div>)}{segments.map(event=><button key={event.segmentId} style={{gridColumn:event.gridColumn,gridRow:event.gridRow,marginTop:`${27+event.segmentOffset}px`}} className={`calendar-event calendar-span ${String(event.priority||'plan').toLowerCase()} ${String(event.status).toLowerCase()} ${event.editable?'editable':''}`} onClick={()=>edit(event)}><span>{new Date(event.date).toLocaleTimeString(locale,{hour:'2-digit',minute:'2-digit'})}</span><b>{eventTitle(event)}</b><small>{event.editable?`${event.patchCode||''} · ${t(String(event.status).toLowerCase())}`:localize(event.assetName)}</small></button>)}</div>{loading&&<div className="calendar-loading"><CalendarDays size={18}/>{t('loading')}</div>}</div>
  <Modal open={!!form} title={form?.id?t('editSchedule'):t('newSchedule')} onClose={()=>setForm(null)} footer={<>{form?.id&&<button className="btn danger" disabled={busy} onClick={remove}><Trash2 size={14}/>{t('delete')}</button>}<span className="modal-spacer"/><button className="btn" onClick={()=>setForm(null)}>{t('cancel')}</button><button className="btn primary" disabled={busy||!form?.titleZh||!form?.titleEn||!form?.patchId||!form?.startAt||!form?.endAt} onClick={save}>{t('save')}</button></>}><div className="form-grid"><label className="form-field"><span>{t('titleZh')}</span><input value={form?.titleZh||''} onChange={e=>setForm({...form,titleZh:e.target.value})}/></label><label className="form-field"><span>{t('titleEn')}</span><input value={form?.titleEn||''} onChange={e=>setForm({...form,titleEn:e.target.value})}/></label><label className="form-field full"><span>{t('patch')}</span><select value={form?.patchId||''} onChange={e=>setForm({...form,patchId:e.target.value})}>{patches.map(p=><option key={p.id} value={p.id}>{p.patchId} · {lang==='zh'?p.titleZh:p.titleEn}</option>)}</select></label><label className="form-field"><span>{t('environment')}</span><select value={form?.environment||'PROD'} onChange={e=>setForm({...form,environment:e.target.value})}><option value="TEST">{t('test')}</option><option value="PREPROD">{t('preprod')}</option><option value="PROD">{t('production')}</option></select></label><label className="form-field"><span>{t('status')}</span><select value={form?.status||'PLANNED'} onChange={e=>setForm({...form,status:e.target.value})}><option value="PLANNED">{t('planned')}</option><option value="APPROVED">{t('approved')}</option><option value="COMPLETED">{t('completed')}</option><option value="CANCELLED">{t('cancelled')}</option></select></label><label className="form-field"><span>{t('maintenanceStart')}</span><input type="datetime-local" value={form?.startAt||''} onChange={e=>setForm({...form,startAt:e.target.value})}/></label><label className="form-field"><span>{t('maintenanceEnd')}</span><input type="datetime-local" value={form?.endAt||''} onChange={e=>setForm({...form,endAt:e.target.value})}/></label><label className="form-field full"><span>{t('notes')}</span><textarea rows="4" value={form?.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div></Modal>
 </>
}
