import React from 'react'
import {RefreshCw,Library,ShieldCheck,Ban,ClipboardList,Workflow,Gauge,ClockAlert,ShieldOff,Rocket} from 'lucide-react'
import {useNavigate} from 'react-router-dom'
import {useApiData} from '../utils/useApiData'
import {useI18n} from '../contexts/I18nContext'
import PageHeader from '../components/PageHeader'
import DataTable from '../components/DataTable'
import StatusBadge,{severityTone,statusTone} from '../components/StatusBadge'
import {severityLabel,envLabel,findingStatus,deploymentStatus,fmtDate} from '../utils/format'

export default function ReportsPage(){
 const {t,pick,localize,lang}=useI18n();const nav=useNavigate();const {data:d,loading,reload}=useApiData('/api/dashboard/report')
 if(loading&&!d)return <div className="loading">{t('loading')}</div>
 const metrics=[['reportTotalLibrary',d?.totalLibrary,Library],['openFindings',d?.openFindings,ShieldCheck],['reportResolved',d?.resolvedFindings,ShieldCheck],['reportExemptions',d?.exemptions,ShieldOff],['slaOverdue',d?.slaOverdue,ClockAlert],['reportOpenTasks',d?.openTasks,ClipboardList],['runningDeployments',d?.runningDeployments,Rocket],['failedDeployments',d?.failedDeployments,Ban],['automationSuccessRate',`${d?.automationSuccessRate??0}%`,Workflow],['patchCompliance',`${d?.patchCompliance??0}%`,Gauge]]
 const maxSev=Math.max(1,...Object.values(d?.severityDistribution||{}));const maxEnv=Math.max(1,...Object.values(d?.environmentDistribution||{}))
 const reasonKey=value=>({KNOWN_EXPLOITED:'reasonKnownExploited',INTERNET_EXPOSED:'reasonInternetExposed',CORE_ASSET:'reasonCoreAsset',EXCEPTION_ACTIVE:'reasonException',CRITICAL_SEVERITY:'reasonCritical'})[value]||'reasonCritical'
 const columns=[{key:'severity',label:t('severity'),render:r=><StatusBadge tone={severityTone(r.severity)}>{severityLabel(t,r.severity)}</StatusBadge>},{key:'cveId',label:t('cve'),render:r=><div className="cell-main"><b className="mono">{r.cveId}</b><small>{pick(r)}</small></div>},{key:'assetName',label:t('asset'),render:r=><div className="cell-main"><b>{localize(r.assetName)}</b><small>{r.assetCode} · {envLabel(t,r.environment)}</small></div>},{key:'riskScore',label:t('riskScore')},{key:'priorityReasons',label:t('priorityBasis'),render:r=><div className="chip-list mini">{r.priorityReasons?.slice(0,3).map(x=><span className="chip" key={x}>{t(reasonKey(x))}</span>)}</div>}]
 const exceptionColumns=[{key:'cveId',label:t('cve'),render:r=><span className="mono linkish">{r.cveId}</span>},{key:'assetName',label:t('asset'),render:r=><div className="cell-main"><b>{localize(r.assetName)}</b><small>{r.assetCode}</small></div>},{key:'severity',label:t('severity'),render:r=><StatusBadge tone={severityTone(r.severity)}>{severityLabel(t,r.severity)}</StatusBadge>},{key:'ownerName',label:t('owner'),render:r=>localize(r.ownerName)},{key:'exemptionReason',label:t('exemptionReason'),render:r=>localize(r.exemptionReason)},{key:'exemptionExpiresAt',label:t('exemptionExpires'),render:r=>fmtDate(r.exemptionExpiresAt,lang)},{key:'status',label:t('status'),render:r=><StatusBadge tone="warn">{findingStatus(t,r.status)}</StatusBadge>}]
 const deploymentColumns=[{key:'deploymentNo',label:t('deploymentNo'),render:r=><span className="mono linkish">{r.deploymentNo}</span>},{key:'patchCode',label:t('patch')},{key:'environment',label:t('environment'),render:r=>envLabel(t,r.environment)},{key:'ring',label:t('ring'),render:r=>localize(r.ring)},{key:'targetCount',label:t('targetCount')},{key:'status',label:t('status'),render:r=><StatusBadge tone={statusTone(r.status)}>{deploymentStatus(t,r.status)}</StatusBadge>},{key:'progress',label:t('progress'),render:r=><div className="progress-cell"><div className="progress"><i style={{width:`${r.progress}%`}}/></div><small>{r.progress}%</small></div>},{key:'createdAt',label:t('createdAt'),render:r=>fmtDate(r.createdAt,lang)}]
 return <><PageHeader title={t('reports')}><button className="btn" onClick={reload}><RefreshCw size={15}/>{t('refresh')}</button></PageHeader><div className="metric-grid report-metrics">{metrics.map(([k,v,Icon])=><div className="metric-card static" key={k}><div className="metric-icon tone-purple"><Icon size={19}/></div><div><span>{t(k)}</span><b>{v}</b></div></div>)}</div><div className="report-grid"><section className="panel"><div className="panel-head"><h2>{t('severityDistribution')}</h2></div><div className="bar-chart">{Object.entries(d?.severityDistribution||{}).map(([k,v])=><div className="bar-line" key={k}><label>{severityLabel(t,k)}</label><div className="bar-track"><i style={{width:`${v/maxSev*100}%`}}/></div><b>{v}</b></div>)}</div></section><section className="panel"><div className="panel-head"><h2>{t('environmentDistribution')}</h2></div><div className="bar-chart">{Object.entries(d?.environmentDistribution||{}).map(([k,v])=><div className="bar-line" key={k}><label>{envLabel(t,k)}</label><div className="bar-track"><i style={{width:`${v/maxEnv*100}%`}}/></div><b>{v}</b></div>)}</div></section></div><section className="panel report-pending"><div className="panel-head"><h2>{t('pendingRemediationList')}</h2><span className="toolbar-count">{d?.pendingFindings?.length||0}</span></div><DataTable columns={columns} rows={d?.pendingFindings||[]} onRowClick={r=>nav(`/vulnerabilities/findings/${r.id}`)}/></section><section className="panel report-pending"><div className="panel-head"><h2>{t('exceptionList')}</h2><span className="toolbar-count">{d?.exceptionFindings?.length||0}</span></div><DataTable columns={exceptionColumns} rows={d?.exceptionFindings||[]} onRowClick={r=>nav(`/vulnerabilities/findings/${r.id}`)}/></section><section className="panel report-pending"><div className="panel-head"><h2>{t('patchInstallationStatus')}</h2><span className="toolbar-count">{d?.recentDeployments?.length||0}</span></div><DataTable columns={deploymentColumns} rows={d?.recentDeployments||[]} onRowClick={r=>r.orchestrationRunId&&nav(`/automation/runs/${r.orchestrationRunId}`)}/></section></>
}
