import React,{useState} from 'react'
import {RefreshCw,Download,Camera} from 'lucide-react'
import {useApiData} from '../utils/useApiData'
import {useI18n} from '../contexts/I18nContext'
import {useAuth} from '../contexts/AuthContext'
import PageHeader from '../components/PageHeader'
import {severityLabel,envLabel,deploymentStatus,fmtDate} from '../utils/format'
import StatusBadge from '../components/StatusBadge'
import {api} from '../api/client'
import {useToast} from '../components/ToastContext'

const csv=value=>`"${String(value??'').replaceAll('"','""')}"`

export default function ReportsPage(){
 const {t,lang,localize}=useI18n();const {has}=useAuth(),toast=useToast();const [days,setDays]=useState(30),[saving,setSaving]=useState(false)
 const {data:d,loading,reload}=useApiData(`/api/dashboard/report?days=${days}`)
 const {data:snapshots=[],reload:reloadSnapshots}=useApiData('/api/dashboard/report/snapshots',{initial:[]})
 const deploymentDistribution=d?.deploymentStatusDistribution||{}
 if(loading&&!d)return <div className="loading">{t('loading')}</div>
 const gauges=[['patchCompliance',d?.patchCompliance??0],['slaComplianceRate',d?.slaComplianceRate??0],['automationSuccessRate',d?.automationSuccessRate??0]]
 const metrics=[['slaOverdue',d?.slaOverdue],['findingsWithoutPatch',d?.findingsWithoutPatch],['criticalInternetExposed',d?.criticalInternetExposed],['reportExemptions',d?.exemptions]]
 const maxSev=Math.max(1,...Object.values(d?.severityDistribution||{})),maxDeploy=Math.max(1,...Object.values(deploymentDistribution))
 const exportReport=()=>{
  const rows=[[t('generatedAt'),d?.generatedAt],[t('reportingWindow'),`${d?.reportingWindowDays} ${t('days')}`],[],[t('metric'),t('value')],...gauges.map(([key,value])=>[t(key),`${value}%`]),...metrics.map(([key,value])=>[t(key),value]),[],[t('severityDistribution'),''],...Object.entries(d?.severityDistribution||{}).map(([k,v])=>[severityLabel(t,k),v]),[],[t('deploymentStatusDistribution'),''],...Object.entries(deploymentDistribution).map(([k,v])=>[deploymentStatus(t,k),v]),[],[t('ownerBacklog'),t('openFindings'),t('slaOverdue')],...(d?.ownerBacklog||[]).map(x=>[x.owner,x.openFindings,x.overdue]),[],[t('riskAssets'),t('assetCode'),t('openFindings'),t('highestRisk')],...(d?.riskAssets||[]).map(x=>[localize(x.assetName),x.assetCode,x.openFindings,x.highestRisk])]
  const blob=new Blob(['\ufeff'+rows.map(r=>r.map(csv).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`gazellio-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)
 }
 const saveSnapshot=async()=>{setSaving(true);try{await api(`/api/dashboard/report/snapshots?days=${days}`,{method:'POST'});toast.success(t('snapshotSaved'));reloadSnapshots()}catch(e){toast.error(e.message)}finally{setSaving(false)}}
 const chart=(title,items,max,label)=><section className="panel"><div className="panel-head"><h2>{title}</h2></div><div className="bar-chart">{Object.entries(items).map(([k,v])=><div className="bar-line" key={k}><label>{label(k)}</label><div className="bar-track"><i style={{width:`${v/max*100}%`}}/></div><b>{v}</b></div>)}</div></section>
 const trend=d?.remediationTrend||[],trendMax=Math.max(1,...trend.flatMap(x=>[x.opened,x.resolved,x.backlog])),points=key=>trend.map((x,i)=>`${trend.length===1?0:i/(trend.length-1)*100},${100-x[key]/trendMax*92}`).join(' ')
 return <>
  <PageHeader title={t('reports')}><select className="report-window-select" value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90,180,365].map(value=><option value={value} key={value}>{value} {t('days')}</option>)}</select><button className="btn" onClick={reload}><RefreshCw size={15}/>{t('refresh')}</button>{has('REPORT_EXPORT')&&<button className="btn" disabled={saving} onClick={saveSnapshot}><Camera size={15}/>{saving?t('processing'):t('saveSnapshot')}</button>}{has('REPORT_EXPORT')&&<button className="btn primary" onClick={exportReport}><Download size={15}/>{t('exportReport')}</button>}</PageHeader>
  <section className="panel report-summary"><div className="panel-head report-summary-head"><div><h2>{t('reportingWindow')} · {d?.reportingWindowDays} {t('days')}</h2><span>{t('generatedAt')} {fmtDate(d?.generatedAt,lang)}</span></div></div><div className="report-stat-row"><div><span>{t('managedAssets')}</span><b>{d?.totalAssets??0}</b></div><div><span>{t('openFindings')}</span><b>{d?.openFindings??0}</b></div><div><span>{t('reportResolved')}</span><b>{d?.resolvedFindings??0}</b></div></div><div className="report-compliance-row">{gauges.map(([key,value])=><div className="report-compliance" key={key}><div><span>{t(key)}</span><b>{value}%</b></div><i><em style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></i></div>)}</div></section>
  <section className="panel report-risk-summary">{metrics.map(([k,v])=><div key={k}><span>{t(k)}</span><b className={(v??0)>0?'risk-value':''}>{v??0}</b></div>)}</section>
  <div className="report-primary-grid"><section className="panel report-trend"><div className="panel-head"><h2>{t('remediationTrend')}</h2><div className="chart-legend"><span className="opened">{t('opened')}</span><span className="resolved">{t('reportResolved')}</span><span className="backlog">{t('backlog')}</span></div></div><div className="report-line-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline className="backlog" points={points('backlog')}/><polyline className="opened" points={points('opened')}/><polyline className="resolved" points={points('resolved')}/></svg><div><span>{trend[0]?.date||''}</span><b>{t('backlog')}: {trend.at(-1)?.backlog||0}</b><span>{trend.at(-1)?.date||''}</span></div></div></section><div className="report-chart-stack">{chart(t('severityDistribution'),d?.severityDistribution||{},maxSev,k=>severityLabel(t,k))}{chart(t('deploymentStatusDistribution'),deploymentDistribution,maxDeploy,k=>deploymentStatus(t,k))}</div></div>
  <div className="report-table-grid"><section className="panel"><div className="panel-head"><h2>{t('ownerBacklog')}</h2></div><table className="report-table"><thead><tr><th>{t('owner')}</th><th>{t('openFindings')}</th><th>{t('slaOverdue')}</th></tr></thead><tbody>{(d?.ownerBacklog||[]).map(x=><tr key={x.owner} onClick={()=>location.assign('/vulnerabilities/findings?q='+encodeURIComponent(x.owner))}><td>{localize(x.owner)}</td><td>{x.openFindings}</td><td className={x.overdue?'danger-text':''}>{x.overdue}</td></tr>)}</tbody></table></section><section className="panel"><div className="panel-head"><h2>{t('riskAssets')}</h2></div><table className="report-table"><thead><tr><th>{t('asset')}</th><th>{t('environment')}</th><th>{t('openFindings')}</th><th>{t('highestRisk')}</th></tr></thead><tbody>{(d?.riskAssets||[]).map(x=><tr key={x.assetId} onClick={()=>location.assign('/assets/'+x.assetId)}><td><b>{localize(x.assetName)}</b><small>{x.assetCode}</small></td><td>{envLabel(t,x.environment)} {x.internetExposed&&<StatusBadge tone="critical">{t('internetExposure')}</StatusBadge>}</td><td>{x.openFindings}</td><td><b>{x.highestRisk}</b></td></tr>)}</tbody></table></section></div>
  <section className="panel report-snapshots"><div className="panel-head"><div><h2>{t('reportSnapshots')}</h2><span>{t('reportSnapshotHint')}</span></div></div><table className="report-table"><thead><tr><th>{t('snapshotNo')}</th><th>{t('reportingWindow')}</th><th>{t('actor')}</th><th>{t('createdAt')}</th></tr></thead><tbody>{snapshots.length?snapshots.slice(0,10).map(x=><tr key={x.id}><td><b>{x.snapshotNo}</b></td><td>{x.windowDays} {t('days')}</td><td>{localize(x.createdBy)}</td><td>{fmtDate(x.createdAt,lang)}</td></tr>):<tr><td colSpan="4" className="empty-cell">{t('noData')}</td></tr>}</tbody></table></section>
 </>
}
