import React,{useEffect,useState} from 'react'
import { ArrowLeft, ExternalLink, UserRoundCog, Wrench, FilePlus2 } from 'lucide-react'
import { useNavigate,useParams } from 'react-router-dom'
import { useApiData } from '../utils/useApiData'
import { api } from '../api/client'
import { useI18n } from '../contexts/I18nContext'
import { useToast } from '../components/ToastContext'
import { useAuth } from '../contexts/AuthContext'
import Modal from '../components/Modal'
import StatusBadge,{severityTone,statusTone} from '../components/StatusBadge'
import {envLabel,incidentStatus,severityLabel,fmtDate} from '../utils/format'
import WorkOrderInsightTabs from '../components/WorkOrderInsightTabs'

function localDateTime(hours=24){const d=new Date(Date.now()+hours*3600000);d.setMinutes(0,0,0);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}

export default function SecurityIncidentDetailPage(){
 const {id}=useParams();const nav=useNavigate();const {t,pick,lang,localize}=useI18n();const toast=useToast();const {has}=useAuth();const {data:x,loading,reload}=useApiData(`/api/work-orders/incidents/${id}`,{poll:10000});const {data:assignees=[]}=useApiData('/api/users/assignees',{initial:[]})
 const [assignOpen,setAssignOpen]=useState(false),[owner,setOwner]=useState(''),[remediationOpen,setRemediationOpen]=useState(false),[patchId,setPatchId]=useState(''),[reason,setReason]=useState(''),[changeOpen,setChangeOpen]=useState(false),[busy,setBusy]=useState(false)
 const [change,setChange]=useState({changeType:'NORMAL',summary:'',riskAssessment:'',implementationPlan:'',rollbackPlan:'',maintenanceStart:localDateTime(24),maintenanceEnd:localDateTime(28)})
 useEffect(()=>{if(x?.ownerId)setOwner(String(x.ownerId));if(x?.patchCandidates?.length&&!patchId)setPatchId(String(x.patchCandidates[0].id));if(x&&!change.summary)setChange(v=>({...v,summary:`${x.cveId} · ${x.businessService||x.assetName} ${t('productionPatchRelease')}`}))},[x?.ownerId,x?.id,lang])
 if(loading&&!x)return <div className="loading">{t('loading')}</div>;if(!x)return null
 const post=async(path,body)=>{setBusy(true);try{await api(path,{method:'POST',body});await reload();toast.push(t('operationSuccess'));return true}catch(e){toast.push(e.message||t('operationFailed'),'red');return false}finally{setBusy(false)}}
 const assign=async()=>{const u=assignees.find(a=>String(a.id)===owner);if(u&&await post(`/api/work-orders/incidents/${id}/assign`,{ownerId:u.id,ownerName:u.displayName}))setAssignOpen(false)}
 const remediate=async()=>{if(await post(`/api/work-orders/incidents/${id}/start-remediation`,{patchId:Number(patchId),reason}))setRemediationOpen(false)}
 const createChange=async()=>{setBusy(true);try{const created=await api(`/api/work-orders/incidents/${id}/changes`,{method:'POST',body:change});setChangeOpen(false);toast.push(t('changeCreated'));nav(`/work-orders/changes/${created.id}`)}catch(e){toast.push(e.message||t('operationFailed'),'red')}finally{setBusy(false)}}
 const canChange=x.status==='PENDING_CHANGE'&&!x.changeOrderId&&(has('CHANGE_CREATE')||has('CHANGE_MANAGE'))
 const taskIsNext=!!x.remediationTaskId&&!canChange&&!x.changeOrderId&&x.status!=='CLOSED'
 const changeIsNext=!!x.changeOrderId&&['PENDING_CHANGE','IMPLEMENTING'].includes(x.status)
 return <>
  <div className="detail-top"><button className="back-button" onClick={()=>nav(-1)}><ArrowLeft size={16}/>{t('back')}</button><div className="detail-actions" role="group" aria-label={t('operationArea')}><button className="btn" onClick={()=>nav(`/vulnerabilities/findings/${x.findingId}`)}><ExternalLink size={15}/>{t('finding')}</button>{(has('INCIDENT_ASSIGN')||has('INCIDENT_MANAGE'))&&<button className="btn" onClick={()=>setAssignOpen(true)}><UserRoundCog size={15}/>{t('reassign')}</button>}{!x.remediationTaskId&&['OPEN','ASSIGNED'].includes(x.status)&&(has('INCIDENT_REMEDIATE')||has('INCIDENT_MANAGE'))&&<button className="btn primary next-action" onClick={()=>setRemediationOpen(true)}><Wrench size={15}/>{t('startRemediation')}</button>}{x.remediationTaskId&&<button className={taskIsNext?'btn primary next-action':'btn'} onClick={()=>nav(`/tasks/${x.remediationTaskId}`)}><ExternalLink size={15}/>{t('remediationTask')}</button>}{canChange&&<button className="btn primary next-action" onClick={()=>setChangeOpen(true)}><FilePlus2 size={15}/>{t('triggerChange')}</button>}{x.changeOrderId&&<button className={changeIsNext?'btn primary next-action':'btn'} onClick={()=>nav(`/work-orders/changes/${x.changeOrderId}`)}><ExternalLink size={15}/>{t('changeOrder')}</button>}</div></div>
  <section className="detail-hero"><div><div className="eyebrow"><StatusBadge tone={x.priority==='P1'?'critical':x.priority==='P2'?'high':x.priority==='P3'?'medium':'low'}>{x.priority}</StatusBadge><StatusBadge tone={statusTone(x.status)}>{incidentStatus(t,x.status)}</StatusBadge><StatusBadge tone={severityTone(x.severity)}>{severityLabel(t,x.severity)}</StatusBadge>{x.kev&&<StatusBadge tone="critical">KEV</StatusBadge>}</div><h1>{x.incidentNo}</h1><h2>{x.cveId} · {pick(x)}</h2></div><div className="score-box"><b>{fmtDate(x.dueAt,lang).split(' ')[0]}</b><span>{t('due')}</span></div></section>
  <WorkOrderInsightTabs record={x} overview={<div className="kv-grid three"><div><span>{t('externalTicket')}</span><b>{x.externalTicketNo||'—'}</b></div><div><span>{t('owner')}</span><b>{localize(x.ownerName)||'—'}</b></div><div><span>{t('businessService')}</span><b>{localize(x.businessService)||'—'}</b></div><div><span>{t('due')}</span><b>{fmtDate(x.dueAt,lang)}</b></div><div><span>{t('createdAt')}</span><b>{fmtDate(x.createdAt,lang)}</b></div><div><span>{t('updatedAt')}</span><b>{fmtDate(x.updatedAt,lang)}</b></div></div>}/>
  <div className="detail-grid"><section className="panel span-2"><div className="kv-grid three"><div><span>{t('externalTicket')}</span><b className="mono">{x.externalTicketNo||'—'}</b></div><div><span>{t('syncStatus')}</span><b>{x.syncStatus}</b></div><div><span>{t('owner')}</span><b>{localize(x.ownerName)||'—'}</b></div><div><span>{t('asset')}</span><b>{localize(x.assetName)}</b></div><div><span>{t('environment')}</span><b>{envLabel(t,x.environment)}</b></div><div><span>{t('businessService')}</span><b>{localize(x.businessService)||'—'}</b></div><div><span>{t('createdAt')}</span><b>{fmtDate(x.createdAt,lang)}</b></div><div><span>{t('updatedAt')}</span><b>{fmtDate(x.updatedAt,lang)}</b></div><div><span>{t('decisionReason')}</span><b>{localize(x.decisionReason)||'—'}</b></div></div></section><section className="panel span-2"><div className="panel-head"><h2>{t('linkedWorkOrders')}</h2></div><div className="workorder-chain"><button className="chain-card current"><span>{t('securityIncident')}</span><b>{x.incidentNo}</b><small>{incidentStatus(t,x.status)}</small></button><i>→</i><button className={`chain-card ${taskIsNext?'actionable':x.remediationTaskId?'ready':'empty'}`} disabled={!x.remediationTaskId} onClick={()=>x.remediationTaskId&&nav(`/tasks/${x.remediationTaskId}`)}><span>{t('remediationTask')}</span><b>{x.remediationTaskNo||'—'}</b><small>{x.remediationTaskId?t('created'):t('notCreated')}</small></button><i>→</i><button className={`chain-card ${changeIsNext||canChange?'actionable':x.changeOrderId?'ready':'empty'}`} disabled={!x.changeOrderId&&!canChange} onClick={()=>x.changeOrderId?nav(`/work-orders/changes/${x.changeOrderId}`):setChangeOpen(true)}><span>{t('changeOrder')}</span><b>{x.changeNo||'—'}</b><small>{x.changeOrderId?t('triggeredByIncident'):canChange?t('readyToTrigger'):t('notCreated')}</small></button></div></section><section className="panel span-2"><div className="panel-head"><h2>{t('patchCandidates')}</h2></div><div className="patch-candidate-grid">{x.patchCandidates?.map(p=><button key={p.id} className="patch-candidate" onClick={()=>nav(`/patches/${p.id}`)}><div><b>{p.patchId}</b><span>{pick(p,'titleZh','titleEn')}</span></div><StatusBadge tone={p.signatureStatus==='VERIFIED'?'ok':'warn'}>{p.signatureStatus}</StatusBadge></button>)}</div></section></div>
  <Modal open={assignOpen} title={t('reassign')} onClose={()=>setAssignOpen(false)} footer={<><button className="btn" onClick={()=>setAssignOpen(false)}>{t('cancel')}</button><button className="btn primary" disabled={!owner||busy} onClick={assign}>{t('confirm')}</button></>}><label className="form-field"><span>{t('assignTo')}</span><select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">—</option>{assignees.map(u=><option key={u.id} value={u.id}>{localize(u.displayName)} · {t(`role_${u.role}`)}</option>)}</select></label></Modal>
  <Modal open={remediationOpen} title={t('startRemediation')} onClose={()=>setRemediationOpen(false)} footer={<><button className="btn" onClick={()=>setRemediationOpen(false)}>{t('cancel')}</button><button className="btn primary" disabled={!patchId||!reason.trim()||busy} onClick={remediate}>{t('confirm')}</button></>}><div className="form-grid"><label className="form-field full"><span>{t('choosePatch')}</span><select value={patchId} onChange={e=>setPatchId(e.target.value)}>{x.patchCandidates?.map(p=><option key={p.id} value={p.id}>{p.patchId} · {pick(p,'titleZh','titleEn')}</option>)}</select></label><label className="form-field full"><span>{t('decisionReason')} *</span><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder={t('patchSelectionBasis')}/></label></div></Modal>
  <Modal open={changeOpen} title={t('triggerChange')} size="lg" onClose={()=>setChangeOpen(false)} footer={<><button className="btn" onClick={()=>setChangeOpen(false)}>{t('cancel')}</button><button className="btn primary" disabled={!change.summary.trim()||!change.riskAssessment.trim()||!change.implementationPlan.trim()||!change.rollbackPlan.trim()||!change.maintenanceStart||!change.maintenanceEnd||busy} onClick={createChange}>{t('submit')}</button></>}><div className="change-source"><span>{t('triggerSource')}</span><b>{x.incidentNo}</b><small>{x.cveId} · {x.assetName}</small></div><div className="form-grid"><label className="form-field"><span>{t('changeType')}</span><select value={change.changeType} onChange={e=>setChange({...change,changeType:e.target.value})}>{['EMERGENCY','MAJOR','NORMAL','STANDARD'].map(v=><option key={v} value={v}>{t(v)}</option>)}</select></label><label className="form-field full"><span>{t('summary')} *</span><input value={change.summary} onChange={e=>setChange({...change,summary:e.target.value})}/></label><label className="form-field"><span>{t('maintenanceStart')} *</span><input type="datetime-local" value={change.maintenanceStart} onChange={e=>setChange({...change,maintenanceStart:e.target.value})}/></label><label className="form-field"><span>{t('maintenanceEnd')} *</span><input type="datetime-local" value={change.maintenanceEnd} onChange={e=>setChange({...change,maintenanceEnd:e.target.value})}/></label><label className="form-field full"><span>{t('riskAssessment')} *</span><textarea rows={3} value={change.riskAssessment} onChange={e=>setChange({...change,riskAssessment:e.target.value})}/></label><label className="form-field full"><span>{t('implementationPlan')} *</span><textarea rows={3} value={change.implementationPlan} onChange={e=>setChange({...change,implementationPlan:e.target.value})}/></label><label className="form-field full"><span>{t('rollbackPlan')} *</span><textarea rows={3} value={change.rollbackPlan} onChange={e=>setChange({...change,rollbackPlan:e.target.value})}/></label></div></Modal>
 </>
}
